### ISSUE TITLE
phxsql 很不错, 有没有可以快速上手的 quick start 手册,或者文档描述?

### ISSUE THREAD

**Issue by theseusyang** [tencent-wechat/phxsql#1]
phxsql 很不错, 有没有可以快速上手的 quick start 手册,或者文档描述?

谢谢!

**Comment by theseusyang** [comment]
比如, phxsql 的二进制下载包的安装、部署等.

**Comment by toontong** [comment]
增加问题：不知道对mysql本身配置有没要求？ 比如必需使用什么引擎；内置自增能不能用；binlog格式有没特殊要求？原binlog是否打开？

**Comment by mariohuang** [comment]
你好，我们已经在本项目内放出了第一个release版本（https://github.com/tencent-wechat/phxsql/releases），其中附有在ubuntu 64bit 下编译的二进制包以及简易安装手册，可直接下载使用
