### ISSUE TITLE
AgentMonitor::CheckRunning() (agent_monitor.cpp:165) 屏蔽了外层的ret变量

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#102]
如题，165行重新声明了ret，这会屏蔽最外层的ret，因此即便这里的检查出错也无法返回错误（而是返回0）：
 int ret = master_manager_->GetMasterInfo(&master_info);

这里的屏蔽似乎不是程序期望的行为？

**Comment by cjcchen** [comment]
已修复

**Comment by zqdai** [comment]
谢谢！
