### ISSUE TITLE
[编译]make: percona/libmysql/libperconaserverclient.a: No such file

### ISSUE THREAD

**Issue by sq-zhang** [tencent-wechat/phxsql#103]
编译并安装完依赖库；

下载了percona-server-5.6_5.6.31-77.0.

make && make install 出现如下错误。

请问该如何解决？谢谢！

<img width="633" alt="qq20170107-0 2x" src="https://cloud.githubusercontent.com/assets/4941496/21741939/47242da8-d51f-11e6-9643-8d213e00d2e0.png">

**Comment by liusifan** [comment]
这里有编译手册：https://github.com/tencent-wechat/phxsql/wiki/%E4%B8%AD%E6%96%87%E8%AF%A6%E7%BB%86%E7%BC%96%E8%AF%91%E6%89%8B%E5%86%8C

直接运行PhxSQL源码根目录build.sh，即可一键完成编译（需要保证网络通畅）

有没有试一下这个一键编译脚本？

**Comment by sq-zhang** [comment]
一键编译不成功，依赖库需要手动编译，缺少许多工具。

--
Zhang Shiqian(张世钱)
School of Software,
Tsinghua University
Beijing 100084, P. R. China
Tel: (+86)18810665765
Email: opassion.thu@gmail.com

**Comment by liusifan** [comment]
如果一键编译不成功，是因为缺少了一些需要用到的工具，那么手工编译也同样会遇到问题啊。

回到一楼说的问题，建议往前看一下，应该先有其他的错误；在前面应该生成 libperconaserverclient.a 的时候可能已经出了其他的错误。编译错误需要按顺序地解决，所以先找一下前面是否有错误。

**Comment by sq-zhang** [comment]
经过不断尝试，已经编译成功。多谢回答。

--
Zhang Shiqian(张世钱)
School of Software,
Tsinghua University
Beijing 100084, P. R. China
Tel: (+86)18810665765
Email: opassion.thu@gmail.com
