### ISSUE TITLE
关于高负载时master不正常过期问题

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#104]
在phxsql负载比较高、而租约比较短（20s）时，master节点有一定的概率会不正常过期，在我们的实验中：
1、在几十个线程并发执行事务时，IO开始变得非常慢（paxos持久化12K数据需要用时约6秒），mysql的事务执行时间普遍过长（> 3s )，
2、phxbinlogsvr对mysql的状态检查是定期采样而且几秒钟就会超时退出。奇怪的是，slave_running的状态检查会与正在发送binlog的事务有竞争而需要等待其执行完毕后才能执行（其他的不会，降低隔离级别也没作用）。因此，该检查会频繁失败，而导致心跳无法发出。
3、高负载下，连续多次检查失败后master的租约就过期了。

这种过期似乎应该是可以避免。我想咨询一下，能不能在发送binlog的时候记录下其起止时间，如果slave_running超时退出，就检查一下是不是当时正在发送binlog，如果是，也认为mysql是健康的？或者是否有其他的办法更好的处理超载问题？

希望官方给予指点，谢谢！

**Comment by zqdai** [comment]
另外，不明白为什么 show status like 'slave_running' 会需要等待正在执行的事务，达人能否给解释一下

**Comment by zqdai** [comment]
不好意思，我又想了下，一开始提到的思路（检查是否在发送binlog）应该是不对的。似乎最好还是把超时退出这种情况单独处理一下比较好，毕竟只有这项检查会超时，其他的如果返回正确值而只有此项超时似乎可以认为是合法的情况？

**Comment by wodesuck** [comment]
重现了一下，确实有这个问题，我的猜测是 show status 中有其它变量跟执行的事务有竞争关系，整个 show status 就阻塞了。

测试了一下，show slave status 是不会阻塞的，改用这个应该可以解决。

多谢你的反馈。

**Comment by zqdai** [comment]
我尝试实现了一下，show slave status似乎问题更大，最后改成检测是否超时了，如果是因为超时，就不当做错误了。。
