### ISSUE TITLE
请教如何降低mysql版本

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#105]
在使用过程中发现系统可能存在版本不匹配的问题，因此想尝试降低phxsql的mysql版本，计划采取以下步骤：
1、目前的版本依赖问题似乎主要来自于phx_percona/percona/sql，我想把低版本的percona的代码中的相同文件进行与这些文件相同的改动后覆盖这些文件
2、使用低版本的percona代码执行完整编译过程

不知以上操作是否有考虑不周全的地方（其他依赖于版本的地方），希望官方指点，谢谢！

**Comment by zqdai** [comment]
god。。。这5.1的代码跟5.6似乎根本不是同一个东西啊，文件名和内容都差别巨大。。 = =

**Comment by wodesuck** [comment]
基本思路就是 diff 一下 phx_percona/percona/sql 看改了哪些（主要改动就是修改了 binlog 相关的 hook point），在别的版本上做同样改动。

不过 5.1 版本可能也太旧了点吧。。

**Comment by zqdai** [comment]
谢谢！的确是太旧了。。绝望地尝试中。。。
