### ISSUE TITLE
请教一下客户端的一些配置问题

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#106]
我们现在用dataneucles做中间件使用phxsql为java做持久化，原先mysql的版本比较老旧（5.1），更换phxsql后发现组件之间一些不兼容的问题（可以基本排除是phxsql的问题，因为直接用percona也有同样的问题），异常也报的比较奇怪：Could not retrieve transation read-only status server，重现概率很低。

所以想请教一下你们是否有使用dataneucles连接phxsql的经验，JDBC connector的版本和JDBC连接池的类型一般如何选择？非常感谢！

目前我们datanucles的版本是3.2.2或者3.2.1，也比较老了。。

**Comment by wodesuck** [comment]
我们主要是用 C++，所有 java 的情况不是很了解。我觉得你可以尝试升级一下客户端版本吧，版本差太远难说会有哪些不兼容的地方。

**Comment by zqdai** [comment]
好的，谢谢！
