### ISSUE TITLE
mysql重启后会出现binlog未被发送的情况

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#109]
文件phxsql/phx_percona/percona/plugin/phxsync_phxrpc/phxsync_utils.cc，149行：

        if (super_read_only == 1)

会导致这个问题。这种情况下binlog未被发送。实际上这种是可能合法出现的。以下步骤可以重现：

1、两台机器构成的phxsql集群，使用restart.py重启所有角色
2、等待十秒左右用mysql执行一个事务，例如：
echo "create database if not exists tmp_phxsql_function_test;" | mysql -uroot -h<host_ip> -P<port> -s
有非常高的概率会出现问题。出现时事务会报因连接断开而执行失败。

经过分析binlog，确认此时被执行的事务为“flush privileges”，似乎是binlogsvr的某个监控线程执行的。

感觉应该把if去掉，无条件执行else部分。

**Comment by wodesuck** [comment]
试了几次暂时没能重现。
按理说这个 if 不应该走到里面，应该必定走到 else 那里，请问有分析出是什么原因走进去吗。

**Comment by zqdai** [comment]
不好意思，写错了一个地方，编辑了一下：重现的环境应是：两台机器构成的集群，重新启动所有角色，然后执行一个事务。。

我也再分析一下为什么会走到if里边去。

**Comment by zqdai** [comment]
日志显示走到if中的原因如下：

1、两个节点，master节点的进程被强制重启后，开始load以前的状态，然而paxos却漏掉了最后一个instance，因此该节点实际上处于落后一个instance的状态。

2、binlogsvr重启后仍然是master，也未过期（因为重启时间很短），因此agent monitor开始初始化mysql的状态到master。只读开关在MASTER_CHANGING状态被关闭，然而执行到状态MASTER_CHANGING_INIT时，执行了flush privileges语句，由于instance落后，因此必然执行失败，导致mysql自杀重启。重启之后只读开关又被打开。但此时，agent monitor已经处于MASTER_CHANGING_INIT状态，结果在只读情况下执行了flush privileges（而且无视只读开关成功执行）。

有两个问题：
1、第一个问题是paxos为何会丢失最后一个instance。我再进一步看一下。
2、第二个问题是agent monitor在MASTER_CHANGING_INIT失败时，状态似乎应该转移回MASTER_CHANGING。

**Comment by zqdai** [comment]
phxpaxos/src/algorithm/instance.cpp, line 177
    for (uint64_t llInstanceID = llBeginInstanceID; llInstanceID < llEndInstanceID; llInstanceID++)
循环退出条件似乎应为 <=

另外，改了这个地方之后还是能够看到事务在super_read_only模式下执行，我再继续看下。。

**Comment by lynncui00** [comment]
1. paxos最后一个instance是通过一轮paxos算法来重新确定的，没有漏掉。
2. 这种情况不会导致Propose操作执行失败。如果是刚启动后的第一个Propose请求，则在Paxos的表现是先将最后一个Instance重新确定，然后重试这个Propose成功。

**Comment by zqdai** [comment]
@lynncui00 谢谢Haochuan！我也意识到了我的理解有误，我再继续看看，为什么我这边mysql第一次发送binlog会有问题。

**Comment by zqdai** [comment]
bug应该在 phxbinlogsvr/core/monitor/agent_monitor.cpp，269行，函数AgentMonitor::CheckMasterInit()，return false相当于在出错的情况下返回了0。这造成了agent monitor不正确的状态转移，并在super_read_only模式下执行了事务。而下一个事务执行时mysql发现上一次的binlog没有发出去。

另外，这个函数里ret被声明了4次。。
