### ISSUE TITLE
PhxSQL 是否能够避免MySQL 的分库分表工作?

### ISSUE THREAD

**Issue by theseusyang** [tencent-wechat/phxsql#11]
从 PhxSQL 的介绍上看, PhxSQL 是 multi-master, 一主多从的架构.那么 来自前端的应用查询可以被路由到多个 master 进行查询操作, 那么是否意味着 PhxSQL 可以避免MySQL 的分库分表工作, 自动进行分库分表了呢?

**Comment by PopeyeZhong** [comment]
👍

**Comment by mariohuang** [comment]
你好，PhxSQL目前专注于MySQL数据从单机扩展到多机并保持一致性上，分库分表暂时并没有在这里实现。但你仍然可以挂载其他分库分表的组件以达到期望的效果。

**Comment by theseusyang** [comment]
那么PhxSQL一主多从可以达到多大的规模呢?

**Comment by theseusyang** [comment]
我以前做过类似 MySQL 的多维分析的 OLAP 平台, 可以线性扩展 DB 的节点.叫做PhoenixDDB。 我可以把相关的经验用在 PhxSQL 上.

**Comment by mariohuang** [comment]
@theseusyang  目前稳定运行最大的集群是5台。
