### ISSUE TITLE
请教一下使用phxsql分库分表的方案

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#110]
想请教一下官方在使用中在phxsql上使用过分库分表的中间件吗？如果有的话，能否帮忙推荐下？谢谢！！

**Comment by liusifan** [comment]
在我们的生产环境中，目前都是由业务自行实现分库分表，还没有使用分库分表的中间件。针对具体的业务场景来定制分库分表方案，以及对应的cache方案，通常来说可以比使用通用的中间件做到更好的性价比。在我们目前的规模和成本约束之下，由业务层实现分开分表是合适的。如果将来需求变化了，或者硬件、网络成本下降了，也可能会使用中间件方案。

**Comment by zqdai** [comment]
谢谢！
