### ISSUE TITLE
有关设置PhxSQL管理员账号密码不成功问题

### ISSUE THREAD

**Issue by 331527583** [tencent-wechat/phxsql#113]
./phxbinlogsvr_tools_phxrpc -f SetMysqlAdminInfo -h 192.168.56.103 -p 17000 -u root -d -U root -D root
get master 192.168.56.103 expire time 1493176751
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
已放弃 (核心已转储)
说明：官方文档提供的命令是phxbinlogsvr_tools而实际上没有发现有这条命令，应该是笔误？
其次，想通过此命令将root初始为空的密码，修改为root。
以上报错，是否由于-d 初始密码为空，导致的报错？如何修改初始root密码为空的情况？有人可以给予帮助么？谢谢

**Comment by zqdai** [comment]
似乎应该写为 -d ""

**Comment by 331527583** [comment]
./phxbinlogsvr_tools_phxrpc -f SetMysqlAdminInfo -h 192.168.56.103 -p 17000 -u root -d "" -U root -D root
get master 192.168.56.103 expire time 1493177588
SetMySqlAdminInfo admin username root -> new admin username root
此命令正确返回。
-d “”是正确的，谢谢@zqdai。BTY，-d“”是不对的。
