### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by hzlpy** [tencent-wechat/phxsql#13]
```
xxx@test-db:/home/happy/workspace/phxsql/sbin$ mysql -uroot -h"192.168.xxx.xxx" -P54321
ERROR 1045 (28000): Access denied for user 'root'@'192.168.xxx.xxx' (using password: NO)
```
在[初始化](https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#初始化phxsql)时报错。请问这种错误会是什么原因导致的？

**Comment by mariohuang** [comment]
有可能是集群初始化时漏掉某个步骤，请按安装指引再次尝试安装，若继续出现此错误，可先使用工具查询下Master是否存在。

**Comment by theseusyang** [comment]
@hzlpy PhxSQL已经正常安装,启动了?

**Comment by hzlpy** [comment]
```
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.2.183" -p 17000
get master 192.168.2.183 expire time 1472816179
machine 192.168.2.183 has been set master(192.168.2.183)

Usage: ./phxbinlogsvr_tools_phxrpc [-c <config>] [-f <func>] [-v]
    -f PHXEcho -s <string>
    -f GetMasterInfoFromGlobal -h <host> -p <port>
    -f GetLastSendGtidFromGlobal -h <host> -p <port> -u<gtid>
    -f SetExportIP -h <host> -p <port>
    -f AddMember -h <host> -p <port> -m <member ip>
    -f RemoveMember -h <host> -p <port> -m <member ip>
    -f SetMySqlAdminInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new admin username> -D <new admin pwd>
    -f SetMySqlReplicaInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new replica username> -D <new replica pwd>
    -f GetMemberList -h <host> -p <port>
    -f InitBinlogSvrMaster -h <ip1,ip2,ip3(ip1 is master, others are slaves)> -p <port>
root@test-db:~/phxsql/sbin# mysql -uroot -h"192.168.2.183" -P54321
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 95
Server version: 5.6.31-77.0-log Source distribution
Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
root@(none) 19:36>
```
上述问题暂时解决了。方法是把 my.cnf 中的 mysql 改为 root ；把编译好的 PhxSQL 放在 /root 目录下，重新执行初始化操作。初始化之前确保 6000,8001,11111,17000,54321等端口对应的进程已被终止。
@theseusyang 从结果来看，我可以进入数据库了。目前还不确定这种解决方式中的两步都是必需的。

**Comment by cjcchen** [comment]
可能是由于不同系统或者不同mMySQL造成的。 请问使用非root启动MySQL是否通过 mysql -uroot -h127.0.0.1 -P默认port 登录进MySQL呢？

**Comment by hzlpy** [comment]
根据[初始化](https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#初始化phxsql)的第 2 步，**在 A 主机执行如下命令**（该命令只在 A 主机执行，IPA 指代 A 主机 IP 地址）
`root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"IPA,IPB" -p 17000`
得到
```
get master IPA expire time 1473055978
machine IPA has been set master(192.168.2.183)
```
然后在 A 主机上执行第 4 步命令：
`mysql -uroot -h"IPA" -P54321`
可以进入 PhxSQL。

但是，在 B 主机上执行如下命令：
`mysql -uroot -h"IPB" -P54321`
却得到如下**错误提示**：
```
root@Vm-template-100G:~/phxsql/tools# mysql -uroot -h"IPB" -P54321
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```
求解~~

**Comment by mariohuang** [comment]
@hlzpy 首先检查下phxsqlproxy进程是否正常存活（一般phxsqlproxy会起两个进程，进程号小的监听54321端口）。若phxsqlproxy正常存货，可以通过~/phxsql/sbin/下的phxbinlogsvr检查IPB上记录的master是什么IP。

**Comment by cjcchen** [comment]
根据初始化
<https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#%E5%88%9D%E5%A7%8B%E5%8C%96phxsql>的第
2 步，*在 A 主机执行如下命令*（该命令只在 A 主机执行，IPA 指代 A 主机 IP 地址）
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f
InitBinlogSvrMaster -h"IPA,IPB" -p 17000
得到

这里看你这个集群已经初始化过了。集群只能初始化一次（InitBinlogSvrMaster）。
最开始初始化的时候是否只初始化了一台机器呢？

例如：./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"IPA" -p 17000

集群初始化后，现在可以通过
./phxbinlogsvr_tools_phxrpc -f GetMasterInfoFromGlobal -h"IPA" -p 17000
来查看当前集群的机器ip

如果不在里面
可以通过
./phxbinlogsvr_tools_phxrpc -f AddMember -h"IPA" -p 17000 -m IPB
加入到集群中


2016-09-05 14:27 GMT+08:00 mariohuang <notifications@github.com>:

**Comment by hzlpy** [comment]
@cjcchen 
```
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"IPA,IPB" -p 17000
```
该命令我只在 A 主机上执行过，并未在 B 主机执行。而且 `InitBinlogSvrMaster` 我也只执行了一次。
现在我通过 `AddMember` 将 B 主机添加到 A 所在的集群中了。主机 A, B 中的 PhxSQL 可以实现同步。

@mariohuang 
但是，我发现我的集群里，A, B 上两个的服务不稳定。短时间内重复执行以下命令，会出现以下现象：
```
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f GetMemberList -h 192.168.2.183 -p 17000
get master fail ret -1

Usage: ./phxbinlogsvr_tools_phxrpc [-c <config>] [-f <func>] [-v]
    -f PHXEcho -s <string>
    -f GetMasterInfoFromGlobal -h <host> -p <port>
    -f GetLastSendGtidFromGlobal -h <host> -p <port> -u<gtid>
    -f SetExportIP -h <host> -p <port>
    -f AddMember -h <host> -p <port> -m <member ip>
    -f RemoveMember -h <host> -p <port> -m <member ip>
    -f SetMySqlAdminInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new admin username> -D <new admin pwd>
    -f SetMySqlReplicaInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new replica username> -D <new replica pwd>
    -f GetMemberList -h <host> -p <port>
    -f InitBinlogSvrMaster -h <ip1,ip2,ip3(ip1 is master, others are slaves)> -p <port>

root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f GetMemberList -h IPA -p 17000
get master IPA expire time 1473059020
ip IPA port 17000
ip IPB port 17000
```

**Comment by cjcchen** [comment]
如果是把一台机器加入到集群，是不需要执行InitBinlogSvrMaster来初始化的。
只需要安装就好了。
InitBinlogSvrMaster 是用于初始化集群。而你现在已经初始化好了，集群已经存在了，因此不再需要执行该步骤。

机器安装的步骤是：
安装PhxSQL（每台机器执行install脚本）
对于其中一台执行InitBinlogSvrMaster，初始化集群，成功后，该机器也成为了Master。

之后如果想把其他机器加入到集群里面，只需要
安装PhxSQL（每台机器执行install脚本）
对已存在的集群执行AddMember。


对于不稳定，需要查看是什么原因。
-1这个应该是表示连接不上机器了。可查看网络是否通畅等。
phxsql也有日志可查看。也可以查看是否有出错日志。从而定位出错原因。


2016-09-05 15:13 GMT+08:00 ZhangLe <notifications@github.com>:

**Comment by hzlpy** [comment]
> 机器安装的步骤是：
安装PhxSQL（每台机器执行install脚本）
对于其中一台执行InitBinlogSvrMaster，初始化集群，成功后，该机器也成为了Master。

@cjcchen ，之前我是如你所说的这样操作的，依旧出现了上述问题，多谢你的回复 : )

**Comment by cjcchen** [comment]
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f
GetMemberList -h IPA -p 17000
get master IPA expire time 1473059020
ip IPA port 17000
ip IPB port 17000


通过这个命令查询到集群已经是两台机器了。因此可以知道该集群已经正常工作了。


请问现在还存在什么问题呢？


在 2016年9月5日 下午3:51，ZhangLe <notifications@github.com>写道：

**Comment by hzlpy** [comment]
> 对于不稳定，需要查看是什么原因。
-1这个应该是表示连接不上机器了。可查看网络是否通畅等。
phxsql也有日志可查看。也可以查看是否有出错日志。从而定位出错原因。

@cjcchen 目前而言，仅存在**不稳定**这个问题了。我准备晚上再测试看看。

**Comment by cjcchen** [comment]
好的。感谢对我们PhxSQL的支持。

在 2016年9月5日 下午4:20，ZhangLe <notifications@github.com>写道：

**Comment by hzlpy** [comment]
```
root@Vm-template-100G:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"IPA,IPB" -p 17000
get master  expire time 0
get master  expire time 0
init master IPA done, start to add member
get master  expire time 0
waiting master to be started
get master  expire time 0
waiting master to be started
get master fail ret -1003
waiting master to be started
get master IPA expire time 1473073118
master started, ip IPA
add ip IPB to master done
```
感觉这样子才是正常的。我自己在主机 A 上建库建表可以同步到主机 B 的 PhxSQL 中。
执行
`./test_phxsql.sh 54321 IPA IPB`
得到的输出是：
```
root@Vm-template-100G:~/phxsql/tools# ./test_phxsql.sh 54321 IPA IPB
create database to phxsql
mysql -uroot -h"IPA" -P54321 -e "create database if not exists test_phxsql;"
create database to phxsql done
create table to phxsql
mysql -uroot -h"IPA" -P54321 -e "use test_phxsql; create table if not exists test_phxsql(name varchar(80));"
create table to phxsql done
insert data to phxsql
mysql -uroot -h"IPA" -P54321 -e "use test_phxsql; insert into test_phxsql values(20160905191022);"
insert data to phxsql done
select data from phxsql
mysql -uroot -h"IPA" -P54321 -e "use test_phxsql; select name from test_phxsql;"
name
20160905191022
select data from phxsql done
select data from phxsql from read/write port
mysql -uroot -h"IPA" -P54321 -e "use test_phxsql; select name from test_phxsql;"
name
20160905191022
select data from phxsql from read/write port done
select data from phxsql from readonly port
mysql -uroot -h"IPA" -P54322 -e "use test_phxsql; select name from test_phxsql;"
name
20160905191022
select data from phxsql from readonly port done
select data from phxsql from read/write port
mysql -uroot -h"IPB" -P54321 -e "use test_phxsql; select name from test_phxsql;"
name
20160905191022
select data from phxsql from read/write port done
select data from phxsql from readonly port
mysql -uroot -h"IPB" -P54322 -e "use test_phxsql; select name from test_phxsql;"
select data from phxsql from readonly port done
root@Vm-template-100G:~/phxsql/tools# 
```

**Comment by cjcchen** [comment]
好的，欢迎继续使用。如有什么问题，欢迎及时联系。

2016-09-05 19:15 GMT+08:00 ZhangLe <notifications@github.com>:
