### ISSUE TITLE
read/write or readonly

### ISSUE THREAD

**Issue by yanghongbo** [tencent-wechat/phxsql#14]
question1：phxsqlproxy 会监听readonly和read/write端口，如果我连接一个slave的phxsqlproxy 的read/write端口来读时，说是请求会被透传到master，这时是和写一样都是操作master的mysql来读还是会在集群中所有的主从mysql中选一个来读。
question2：在实际应用中使用读时，readonly和read/write的选择上有什么建议

**Comment by mariohuang** [comment]
1. 请求会透传到Master，但对应用来说这个透传是完全透明的。
2. 对于读非常多但对实时性要求并非最高的服务，我们建议用readonly端口，可以把slave的性能利用起来。
