### ISSUE TITLE
真心难搞，不实用！

### ISSUE THREAD

**Issue by starcrafty** [tencent-wechat/phxsql#15]

**Comment by mariohuang** [comment]
@starcrafty 请问具体是卡在哪一步？

**Comment by starcrafty** [comment]
依赖太多，安装过于繁琐，觉得应该在流程上进行较大改进

**Comment by BlueseaFinTech** [comment]
我用的CentOS 6.x ,各种不兼容，官方可否出些文档把不同系统上的依赖写清楚，自己折腾有点费劲，ubuntu没那么多人用吧，这个项目的功能还是不错的，希望安装部署这块有更好的改进。

**Comment by mariohuang** [comment]
@BlueseaFinTech 是在编译什么模块的时候提示不兼容？

**Comment by lynncui00** [comment]
@BlueseaFinTech 您好，我们已经编写了详细的编译手册，希望能帮助到您，请查看我们的WIKI。

**Comment by jingyihome** [comment]
@BlueseaFinTech  我在CentOS6 和Centos7 下编译成功，CentOS系统自带的或者yum安装的工具版本太低，很多工具都要升级，下面是我在CentOS6下编译的过程 。[文章地址](http://www.zhanghaijun.com/post/968/)

**Comment by starcrafty** [comment]
-DWITHOUT_TOKUDB=1 不加这个就是一直报错的节奏啊 
提示 -fuse-linker-plugin 这个错误

**Comment by starcrafty** [comment]
install完成后，二进制会生成到PhxSQL目录下的sbin目录，运行所需要的相关文件和配置会安装到PhxSQL目录下的install_package目录。打包二进制运行包会把install_package进行tar格式的打包，并生成phxsql.tar.gz。若想更改install的安装目录，可在sh autoinstall.sh 后加入-prefix=路径

这个文字描述里 -prefix修改成--prefix

**Comment by wkshare** [comment]
建议提供一些版本，已编译好的二进制版本。
使用者，技术参差不齐。二进制最便捷，推广使用会更好

**Comment by toontong** [comment]
文档中的提到  tools/install.py 文件，已消失于 最新代码中。
要中文编译文档，依然会遇到：
Linking CXX shared module phxsync_master_phxrpc.so
/bin/ld: cannot find -lphxglog

**Comment by mariohuang** [comment]
@toontong 不好意思给你造成误解，这里提到的install.py是在编译后打出的安装包中的，对应目前源代码是phxsql/phxrpc_package_config/tools/install.py。另外按你贴的出错提示，应该是glog的编译有问题引起的，请根据编译指引下载对应的glog版本，从头编译试试。

**Comment by toontong** [comment]
third_party/autoinstall.sh  能运行成功，最终打印出all done
并且  third_party/glog/lib/libglog.1a 文件编译出来了，重编译结果也一样~
那么此脚本（third_party/autoinstall.sh）应该有bug~

**Comment by starcrafty** [comment]
问题解决的了，主要还是gcc环境升级的问题
只是觉得环境要搞的太多，有点烦杂

**Comment by wodesuck** [comment]
添加了Travis CI进行自动构建。https://travis-ci.org/tencent-wechat/phxsql 可查看构建状态。
构建有困难也可以参考构建脚本build.sh。
