### ISSUE TITLE
PhxSQL管理

### ISSUE THREAD

**Issue by hzlpy** [tencent-wechat/phxsql#16]
- 修改密码

```
root@test-db:~/phxsql/sbin# ./phxbinlogsvr_tools_phxrpc -f SetMySqlAdminInfo -h IPB -p 17000 -u root -d '' -U happy -D happy
get master IPB expire time 1473154666
SetMySqlAdminInfo fail ret -202
```
请问，返回 -202 是什么意思？

- 重启 phxbinlogsvr

[phxbinlogsvr故障处理](https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#phxbinlogsvr故障处理)提到

> 在重装过程中，phxbinlogsvr可能会拉取集群内其他机器checkpoint来启动，待checkpoint拉取结束后，phxbinlogsvr会自杀（为了确保数据安全），日志中会出现"All sm load state ok, start to exit process"，此时须重新启动phxbinlogsvr，启动后会正常运行。

请问，怎样重新启动 phxbinlogsvr？是否是执行 tools/restart.py ？

**Comment by berockguo** [comment]
202的意思是REQ_INVALUD
