### ISSUE TITLE
是否有文档能详细描述一下phxsql的安装过程？

### ISSUE THREAD

**Issue by kidactor** [tencent-wechat/phxsql#17]
感觉安装过程中有部分依赖的内容没有列出来，也比较容易出错，也不太确定最终环境是否能和官方的安装结果一样。

**Comment by hzlpy** [comment]
[安装 PhxSQL 笔记](http://chuzhiyan.com/2016/09/01/%E5%AE%89%E8%A3%85-PhxSQL-%E7%AC%94%E8%AE%B0/) : )

**Comment by lynncui00** [comment]
@kidactor  您好，我们已经编写了详细的编译手册，请查看我们的WIKI。

**Comment by jingyihome** [comment]
我在CentOS6 和Centos7 下编译成功，使用CentOS系统的可以交流下[文章地址](http://www.zhanghaijun.com/post/968/)

**Comment by lynncui00** [comment]
@jingyihome 非常有用的文章，已添加到WIKI帮助更多的CentOS开发者。

**Comment by lynncui00** [comment]
@jingyihome boost这一步可以省略，这个不是必要的。

**Comment by jingyihome** [comment]
@lynncui00 好的，我把这一步去掉，我之前编译的时候有一步make boost的需要boost当时就编译了，文章整理的时候就把这一步也加进去了。
