### ISSUE TITLE
phxsql 对MySQL配置是否有特殊要求？

### ISSUE THREAD

**Issue by toontong** [tencent-wechat/phxsql#2]
- 比如存储引擎；
- 内置自增能不能用；
- binlog格式有没特殊要求，原binlog是否要打开？
- 内置的mysql/slave机制是否配置？
- 能否不经phx-porxy直接在任意的mysql节点上进行写操作？

....

**Comment by mariohuang** [comment]
你好
- 比如存储引擎；
PhxSQL利用的是MySQL两阶段提交的特性，所以对存储引擎的要求是必须支持MySQL的这个特性，比如InnoDB。
- 内置自增能不能用；
可以
- binlog格式有没特殊要求，原binlog是否要打开？
binlog是我们同步方案的核心，需要打开且至少设置为mixed
- 内置的mysql/slave机制是否配置？
不需要用户配置，直接使用即可。
- 能否不经phx-porxy直接在任意的mysql节点上进行写操作？
不能，我们要求所有写操作都经过proxy，对mysql节点进行写操作，比如ddl操作，可能对数据库造成不可逆的数据不一致。

**Comment by toontong** [comment]
再追问： 看架构 ，在一台机上只有一个proxy的情况下，proxy 应该是单点的吧？ 

挺好~ 赞。 增加个Q&A的wiki页，就可以close

**Comment by mariohuang** [comment]
你好，

proxy并不能认为是单点，单个存活与否并不影响整个集群的可用性，client可通过失败重试/架设VIP等方法绕开不可用的proxy。

**Comment by toontong** [comment]
您好，感谢回答。
proxy高可用这块跟我想的一致。

再追问，

- proxy是否实现是对连接的收敛?

> 即 对于 client端100连接到proxy时，proxy连接my
> sql只使用10个，原因是有90个client 的连接是idle的，从而达到proxy->mysql的连接重用。
> 还是 说proxy实现的是1对1的TCP代理？
 
- 是否支持对写端口进行读sql的发送？ 如支持是否会全落在同一个写节点上？
- phsql是否已经用于微信产品（生产环境），使用量在什么级别？ 经历多了时间 的验证？

**Comment by mariohuang** [comment]
你好，考虑到MySQL事务是以链接为单位，我们并未作链接收敛。目前是一个1对1的TCP透传。
我们的读写端口支持任何读写操作，并保证读取到最新数据，读端口不保证读取到最新数据，不支持写请求。PhxSQL已经在微信生产环境中稳定使用超过半年。最大的集群为11个表，800万行数据，读高峰超过6万QPS（5机集群）。欢迎试用。

**Comment by toontong** [comment]
> 运维简单：PhxSQL集群内机器出现短时间故障，能自动恢复数据，无需复杂的运维操作；PhxSQL更提供一键更换（新增/删除）集群内的机器，简化运维的工作。
README.md 中提及的“运维简单”，并没对 master（写节点）宕机与读节点宕机情况进行说明。

能否说说，这 两种情况：

- 若写宕机，还能否写入？
- 什么节点宕机或进程服务（proxy，phxlogsvr), 才会部分不可用？ 短时间故障是多短，并能自动恢复？

**Comment by cjcchen** [comment]
写宕机会发生Master切换。可以通过转移proxy来继续写入。
短期故障这个是按照各机器的数据是否还保留来决定时间长度。机器恢复工作后会去其他机器获取数据。如果其他机器的数据还在，则可自动恢复。如果数据已删，则需要手工恢复。
由于磁盘大小有限制，因此每一台机器不能永久保存所有数据。必须根据配置时间定期清理。

在 2016年9月1日 上午9:39，Huang ChuanTong <notifications@github.com>写道：
