### ISSUE TITLE
./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.9.131,192.168.9.132,192.168.9.133" -p 17000  返回get master expire time 0，后漫长等待 

### ISSUE THREAD

**Issue by xrootman** [tencent-wechat/phxsql#20]
你好，
环境：centos 6.6
过程描述：各组件正常编绎，初始化完成
错误现象：
./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.9.131,192.168.9.132,192.168.9.133" -p 17000

get master expire time 0
get master expire time 0
get master expire time 0
漫长等待后
init svr fail, ret -1
经多套环境下测试都是这个提示，请指导。

**Comment by xrootman** [comment]
补充错误日志信息：
日志名：phxbinlogsvr.mysql.log.ERROR.20160908-103404.6728
E0908 10:37:05.674700 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:06.000730 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:06.675972 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:07.000255 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:07.677012 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:08.000396 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:08.678822 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:09.000048 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:09.679617 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:09.738741 6825 phx_glog.cpp:82] ^[[46;34m DoQuery mysql_query show global variables like 'gtid_executed'; done 0, ^[[0m
E0908 10:37:09.738905 6825 phx_glog.cpp:82] ^[[46;34m MakeCheckPoint now time 1473302229 last check time 1473302184, interval time 216000 ^[[0m
E0908 10:37:09.738935 6825 phx_glog.cpp:82] ^[[46;34m MakeCheckPoint check point check done ^[[0m
E0908 10:37:09.740269 6825 phx_glog.cpp:82] ^[[46;34m CheckRunningStatus current mysql instanceid 0, binlog svr instanceid 0 ^[[0m
E0908 10:37:10.000268 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:10.680131 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:11.000282 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:11.680572 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:12.000707 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:12.682564 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m
E0908 10:37:13.001195 6918 phx_glog.cpp:82] ^[[46;34m Process master is not inited, waiting init, doing nothing ^[[0m
E0908 10:37:13.684191 6914 phx_glog.cpp:82] ^[[45;37m Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instan
ceid (no checkpoint) now instanceid 0 ^[[0m

日志名：phxsqlproxy.mysql.log.ERROR.20160908-103403.6735

Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0908 10:34:03.725553 6769 phx_glog.cpp:82] ^[[46;34m ReadAgentConfig read agent config ^[[0m
E0908 10:34:03.726379 6769 phx_glog.cpp:82] ^[[46;34m ReadAgentConfig load db path /apps/data/phxsql/phxbinlogsvr/event_data engine ip 192.168.9.13
1 port 6000 package name phxbinlogsvr ^[[0m

尝试在另外机器上执行：
[mysql@oldboy66-23 sbin]$ ./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.9.131,192.168.9.132,192.168.9.133" -p 17000

get master fail ret -1
connect machine 192.168.9.131 fail
init svr fail, ret -1

**Comment by xrootman** [comment]
在执行该语句后
./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.9.131,192.168.9.132,192.168.9.133" -p 17000 
发现phxproxy进程被杀。

**Comment by mariohuang** [comment]
@xrootman 我们已发现该问题并fix，修复方法如下：
1、重新clone一份libco代码，覆盖third_party下的libco并执行make
2、进入phxsqlproxy目录，执行 make clean; make phxsqlproxy_phxrpc
3、检查phxsqlproxy目录下的phxsqlproxy_phxrpc的更新时间是否是刚生成的，若是，则复制其覆盖原有的原目录下的sbin/phxsqlproxy_phxrpc
4、重新执行python restart.py -pphxsqlproxy并观察是否修复。

谢谢你的反馈，欢迎继续试用:)

**Comment by cjcchen** [comment]
@ZhangLe 这是某些系统的cpu指令集的问题。如果没有遇到该问题的，可以先忽略。

2016-09-09 23:43 GMT+08:00 ZhangLe <notifications@github.com>:
