### ISSUE TITLE
增加节点是否意味着增加集群处理性能

### ISSUE THREAD

**Issue by xxj123go** [tencent-wechat/phxsql#22]
增加节点是否意味着增加集群处理性能

**Comment by cjcchen** [comment]
增加节点会降低集群的写性能，因为每个写请求需要同步到集群中的多数派机器。
所以一般建议使用3-5个节点的集群。

而对于读多写少的场景，如果允许读备机数据，增加节点可以提高集群的读性能。

2016-09-12 17:33 GMT+08:00 xxj123go <notifications@github.com>:
