### ISSUE TITLE
扩容问题

### ISSUE THREAD

**Issue by xxj123go** [tencent-wechat/phxsql#23]
如果考虑到后期系统规模越来越大，如何增加集群处理能力，昨天我问了个问题，就是增加节点和集群能力的系统是不是正相关，得到的回答貌似不是 ，那集群的处理能力是如何增加的（除了常规的分库分表，读写分离等）

**Comment by berockguo** [comment]
部署多个phxsql实例呀

**Comment by lynncui00** [comment]
@xxj123go 您好，目前phxsql致力于一致性和高可用上，对于横向扩展行没有增强，横向扩展还是要由业务自行解决。或者考虑自行组合一些已有的横向扩展的方案。

**Comment by xxj123go** [comment]
@lynncui00  这和微信用的不是一套吗，你微信那么大用户量是怎么做扩展

**Comment by liusifan** [comment]
@xxj123go phxsql对于扩展性没有提供额外的增强，开源的代码和我们内部使用的是同一份。我们内部使用 phxsql 的时候，如果需要扩容，目前仍然是需要人工操作的。使用的扩展方式也是分库分表这类常规的方式。

**Comment by larrymeng** [comment]
get
