### ISSUE TITLE
断电的机器仍然在MemberList中是期望的行为吗

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#25]
如题。假设3台机器的集群，某台机器断电后，GetMemberList仍然可以看到该机器，请问这是系统期望的行为吗？

**Comment by lynncui00** [comment]
是的。memberlist的变更取决于用户进行的主动修改(如何修改成员请参考WIKI)，而不会对受灾的机器进行自动剔除。

**Comment by zqdai** [comment]
明白了，谢谢！
