### ISSUE TITLE
Master节点断网后有些Slave的状态不正确

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#26]
如题，该问题可以较为稳定的重现。

配置：ubuntu 14.04，virtual box 4台虚拟机。

启动4台机器并测试集群可以正常服务后，将master网络切断。观察到如下行为：
1、数秒钟后master自动切换。
2、依次测试新master和另外两台slave的读写端口和读端口（进行简单的插入和查询操作）。发现总有某个slave机器状态或者功能异常，目前遇到过以下几种情况：
a. 无法连接slave的读写口（只读端口连接查询正常）：ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
b. 可以连接slave的读写口：但读端口显示super_read_only为OFF，而读写端口此变量值为ON

当错误类型为a时重新启动phxsqlproxy后恢复正常。b暂时未能重现。

**Comment by cjcchen** [comment]
@zqdai 请问当问题a出现的时候，可否查询下master的ip和他的租约超时时间？并观察机器当前时间。

通过进入phxsql/tools目录，执行phxbinlogsvr_tools -f GetMasterInfoFromGlobal -h 问题机器IP -p 17000
返回master ip， 租约时间。

当问题a出现的时候，通过多次重试，或者等待一定时间后，该问题是否能解决？

**Comment by zqdai** [comment]
@cjcchen 不好意思，该问题在我重新安装测试后（因为机器IP变化，原先的安装不能使用了）暂时未能重现，如果将来重现会按照你指导的步骤来获取相关信息。

根据当时的情况，等待过数分钟后问题依然存在（实际上，一开始两台slave均有问题，后来一台自动恢复了，而另一台则未能自动恢复）。问题机器经过重新启动一些进程或者机器后是可以恢复正常的。

**Comment by cjcchen** [comment]
从表现上看应该是机器ip有变动导致proxy找不到对应的ip产生的。
如果后续仍然遇到该问题，欢迎前来反馈。

在 2016年9月18日 上午10:47，zqdai <notifications@github.com>写道：

**Comment by zqdai** [comment]
@cjcchen 最新发现的issue，同样的场景：4台ubuntu virtual box虚拟机搭建集群，运行自带的测试脚本几次，然后断开Master节点的网络（虚拟机模拟网线断开，所有服务继续运行），待Master切换成功后再运行自带的测试脚本数次，然后恢复原来的master机器的网络，可以观察到：故障节点以Slave身份重新加入了集群，但在mysql的本地端口（11111）可以看到super_read_only变量仍为OFF。一段时间之后恢复正确（ON）。

我猜测可能在该场景下故障节点的状态切换代码并未执行，然后在新的master租约到期时代码才执行，请协助确认，谢谢！

**Comment by cjcchen** [comment]
请问在该旧Master机器上通过proxy（54322端口）连接MySQL，看到的super_read_only是否也为off？
当网络节点重新加入时，该机器上的phxbinlogsvr是从断开网络前一直保持运行着还是重新启动？


在 2016年9月19日 下午7:48，zqdai <notifications@github.com>写道：
