### ISSUE TITLE
提问：集群中其他机器的配置信息在哪里

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#27]
如题，在配置文件中只有本机的信息，想知道其他机器的信息存储在何处，是否可以手动配置。

因为我测试的环境机器的IP是动态分配的，因此IP经常会变化，变化之后发现原先的安装就不能再用了（但重新安装会丢失所有的数据）。所以想请教一下如何在不重新安装的情况下更换集群中其他机器的IP地址？或者是否可以增加一些管理功能，以便更换机器的IP？

另外从前面的讨论中我也了解到有些信息，比如Server的ID是依赖于IP的，请问IP变化后这些信息是否会相应地进行更新？谢谢。

**Comment by mariohuang** [comment]
集群的成员管理（membership）由phxbinlogsvr负责，会经过paxos广播后落地存储，用户可通过sbin/phxbinlogsvr_tools_phxrpc工具查看并管理该集群。由于动态IP会使设计复杂度提升较多，且实际生产环境中使用动态IP的情况较少，我们目前并未支持动态IP，建议你直接手动分配IP后再进行测试。

**Comment by zqdai** [comment]
谢谢mario!

**Comment by cjcchen** [comment]
phxsql通过ip加端口用来标志集群中的机器，如果集群中机器的ip经常发生变化，会导致节点找不到，通讯失败之类的问题产生。因此phxsql集群中的ip都是需要固定的。

如果需要更换ip，可以尝试进行成员管理的操作。成员管理的具体步骤可查看readme和wiki中的相关文档。
谢谢

2016-09-18 13:16 GMT+08:00 zqdai <notifications@github.com>:
