### ISSUE TITLE
提问：对于proxy不可用有哪些正确的防范方法？

### ISSUE THREAD

**Issue by hushulin** [tencent-wechat/phxsql#28]
某个节点的phxsqlproxy不可用，可以用失败重试/架设VIP等方式。请问，失败重试的具体做法和架设VIP的具体做法是什么，用keepalived做高可用可以吗？能做的话，具体怎么做？

**Comment by mariohuang** [comment]
PhxSQL三机对外提供的功能是完全一致的，所以为无状态服务设计的高可用方案都可以应用在PhxSQL上，具体到问题中的的做法，我稍加解释下：
假设你架设的是一个三机（ABC）的PhxSQL集群，在访问机器A时失败了，可以简单的选择B或C机访问。这个就是失败重试了。
架设VIP简单说就是把上面重试的过程屏蔽掉，使得客户端每次看到的都是同一个IP，简化客户端的设计。
因为三机是对等的，选用 keepalived当然也是可以的。

**Comment by hushulin** [comment]
谢谢，跟我当时的设想是一样的
