### ISSUE TITLE
TPCC-MYSQL测试失败

### ISSUE THREAD

**Issue by aStonegod** [tencent-wechat/phxsql#30]
Hi,首先感谢分享phxsql。我用tpcc进行测试，出现一些问题，官方是否可以给出答复？

<Raw Results>
  [0] sc:0  lt:0  rt:109837  fl:56 
  [1] sc:0  lt:0  rt:114389  fl:56 
  [2] sc:0  lt:0  rt:13016  fl:6 
  [3] sc:6  lt:0  rt:0  fl:0 
  [4] sc:0  lt:0  rt:11858  fl:5 
 in 100 sec.

<Raw Results2(sum ver.)>
  [0] sc:0  lt:0  rt:109872  fl:56 
  [1] sc:0  lt:0  rt:114434  fl:56 
  [2] sc:0  lt:0  rt:13016  fl:6 
  [3] sc:6  lt:0  rt:0  fl:0 
  [4] sc:0  lt:0  rt:11859  fl:5 

<Constraint Check> (all must be [OK])
 [transaction percentage]
        Payment: 0.00% (>=43.0%) [NG] *
   Order-Status: 0.00% (>= 4.0%) [NG] *
       Delivery: 100.00% (>= 4.0%) [OK]
    Stock-Level: 0.00% (>= 4.0%) [NG] *
 [response time (at least 90% passed)]
      New-Order: -nan%  [NG] *
        Payment: -nan%  [NG] *
   Order-Status: -nan%  [NG] *
       Delivery: 100.00%  [OK]
    Stock-Level: -nan%  [NG] *

<TpmC>
                 0.000 TpmC
:~/tpcc-mysql# ./tpcc_start -h 192.168.1.71 -P 54325 -utpcc -ptpcc  -dtpcc -w10 -c10  -r10 -l100

PS:  SYSBENCH, MYCATTOOL等工具直接写入都是成功的。

**Comment by wodesuck** [comment]
先确认一下测试数据有成功load进去，你的测试输出看上去像是数据没有load进去的结果。
我在重现过程中发现tpcc_load会因为一次commit内容太多导致失败，修改一下load.c让它分批commit可解决。

**Comment by wodesuck** [comment]
看了一下tpcc_start应该也是有单个事务太大的问题，这个是受限于我们的paxos限制了单包大小不能超过50M，实际应用中很少需要这种场景，因此没做特殊支持。
