### ISSUE TITLE
phxsql 对比percona xtradb cluster 的长处短处在哪？

### ISSUE THREAD

**Issue by wushaobo** [tencent-wechat/phxsql#31]
看到phxsql是依赖于percona server的集群实现，就好奇它比percona自己实现的集群 [percona xtradb cluster](https://www.percona.com/software/mysql-database/percona-xtradb-cluster) 的长处和短处在哪里，可否基于mysql 5.6这个版本辨析下这个问题？ 

我自己是pxc的用户，当然欢迎比pxc更好的实现。看到[你们在percona forums里的帖](https://www.percona.com/forums/questions-discussions/mysql-and-percona-server/45807-phxsql-a-high-availability-and-strong-consistency-mysql-cluster)还没人回应

**Comment by mariohuang** [comment]
关于PhxSQL的设计以及与其他方案的对比，可以参考我们官方对于方案的一些思考

[谈谈PhxSQL的设计和实现哲学（上）](http://mp.weixin.qq.com/s?__biz=MzI4NDMyNTU2Mw==&mid=2247483790&idx=1&sn=c925202df42c54422db9a134ea764eac#rd)
[谈谈PhxSQL的设计和实现哲学（下）](http://mp.weixin.qq.com/s?__biz=MzI4NDMyNTU2Mw==&mid=2247483795&idx=1&sn=233f803d9af3cd31e551ac0709f682ec#rd)
