### ISSUE TITLE
FATAL ERROR: Error closing mysqld pipe: Broken pipe

### ISSUE THREAD

**Issue by ninglianjie** [tencent-wechat/phxsql#33]
我在编译打包过程中没有遇到问题, 但是在部署的时候, install.py脚本报了如下错误, 请问是什么原因导致的?

Namespace(agent_port=6000, base_dir='/home/phxsql/', data_dir='/home/phxsql/data/', inner_ip='10.86.41.1', ip_list='10.86.41.1', module_name='test', mysql_port=11111, paxos_port=8001, phxbinlogsvr_port=17000, phxsqlproxy_port=54321, process_name='all')
kill all binaries success....
mkdir: cannot create directory `/home/phxsql//etc': File exists
generate all configs success....
mkdir: cannot create directory `/home/phxsql/data//log': File exists
/home/phxsql/data//phxbinlogsvr
mkdir: cannot create directory `/home/phxsql/data//log': File exists
/home/phxsql/data//percona.workspace
chown: invalid user: `user:mysql'
cd /home/phxsql//percona.src; ./scripts/mysql_install_db --defaults-file=/home/phxsql//etc/my.cnf --user=mysql
Installing MySQL system tables...2016-09-21 10:42:25 0 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
2016-09-21 10:42:25 0 [Note] ./bin/mysqld (mysqld 5.6.31-77.0-log) starting as process 18422 ...
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......

**Comment by mariohuang** [comment]
这个是在安装PhxSQL的mysql实例时失败，可按安装MySQL的经验进行debug，根据你提供的日志，似乎/home/phxsql/data/里面原来有过数据，如果有的话，请rm掉再重试看看。

**Comment by zqdai** [comment]
在SUSE上也遇到了这个问题。两台机器环境其实是一样的，从一台编译的package拿到另一台发生了这个错误。

目前我这边看到的是 mysql_install_db 这个perl脚本执行出错。对perl脚本不熟悉，报的错误很奇怪，说某个 { 附近有语法错误。更奇怪的是编译phxsql的机器上则完全没有问题。

**Comment by ninglianjie** [comment]
我猜测是自动生成的配置文件有问题. 如果不指定my.cnf配置文件, 直接指定一个datadir就可以初始化成功, 如下:
`# cd /home/q/phxsql//percona.src; ./scripts/mysql_install_db --datadir=/tmp/data --user=mysql
Installing MySQL system tables...2016-09-21 20:48:29 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-09-21 20:48:29 0 [Note] ./bin/mysqld (mysqld 5.6.31-77.0) starting as process 1868 ...
2016-09-21 20:48:29 1868 [Note] InnoDB: Using atomics to ref count buffer pool pages
2016-09-21 20:48:29 1868 [Note] InnoDB: The InnoDB memory heap is disabled
2016-09-21 20:48:29 1868 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
...
...

# ll /tmp/data
total 110616
-rw-rw---- 1 mysql mysql 12582912 Sep 21 20:48 ibdata1
-rw-rw---- 1 mysql mysql 50331648 Sep 21 20:48 ib_logfile0
-rw-rw---- 1 mysql mysql 50331648 Sep 21 20:48 ib_logfile1
drwxr-xr-x 2 root  root      4096 Sep 21 20:47 log
drwx------ 2 mysql mysql     4096 Sep 21 20:48 mysql
drwxr-xr-x 6 root  root      4096 Sep 21 20:47 percona.workspace
drwx------ 2 mysql mysql     4096 Sep 21 20:48 performance_schema
drwxr-xr-x 3 root  root      4096 Sep 21 20:47 phxbinlogsvr
drwx------ 2 mysql mysql     4096 Sep 21 20:48 test
`

**Comment by ninglianjie** [comment]
解决了. 下面的这两个脚本的问题.
把director_operator.py文件第26行中的chown user:mysql 修改为chown mysql:mysql
把binary_installer.py文件第35行中的 cd %s/percona.src; ./scripts/mysql_install_db --defaults-file=%s/etc/my.cnf 修改为：cd %spercona.src; ./scripts/mysql_install_db --defaults-file=%setc/my.cnf
