### ISSUE TITLE
phxbinlogsvr_tools设置管理员密码问题

### ISSUE THREAD

**Issue by coding-chenkaikai** [tencent-wechat/phxsql#34]
通过phxbinlogsvr_tools设置mysql非root管理员及密码，使用命令如下：
`phxbinlogsvr_tools -f SetMySqlAdminInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new admin username> -D <new admin pwd>`
1、通过phxsql集群中主机登陆mysql，非root用户，密码正常，登陆成功
2、通过phxsql集群外主机登陆mysql，非root用户，提示密码不正确，经测试密码为空
3、想通过phxsql集群外主机登陆mysql，使用root登陆，发现没有权限，通过查看mysql权限表，没有给root分配其他主机访问的权限？

**Comment by mariohuang** [comment]
1 2 能否给出登录的指令，密码可以不用贴出来？
3这点是我们想做到与原生MySQL安装后一样的安全标准，原生MySQL安装后root只有localhost的登陆权限，所以扩展到PhxSQL上，安装后就只能三台集群内的机器能登录，这样避免了用户安装后没修改密码，被坏人进行扫描攻击的风险。如果你有其他机器访问PhxSQl的需求，请直接对PhxSQL进行IP授权的操作。

**Comment by coding-chenkaikai** [comment]
基本信息如下：
集群主机：ip1,ip2,ip3
集群外主机：ip0
phxsqlproxy_port：19521
设置新用户名／密码：newuser／newpassword
登陆指令如下：
mysql -unewuser -P19521 -h ip1 -p"newpassword" 
【提示：ERROR 1045 (28000): Access denied for user 'newuser'@'ip1' (using password: YES)】
mysql -unewuser -P19521 -h ip1
【登陆成功】

**Comment by aStonegod** [comment]
这个问题我也遇到过， 重新部署之后正常了.....

**Comment by cjcchen** [comment]
@coding-chenkaikai 请问是修改了用户密码之后，在集群内登陆时，用新的用户和密码也是登陆不成功吗？

对于集群外的ip，是需要用户自己手动授权的。我们默认只对集群内的ip能使用管理员权限登陆。

**Comment by coding-chenkaikai** [comment]
@cjcchen 在集群内部是可以使用新用户名和新密码登陆成功的，在集群外部，密码就变为空了

**Comment by cjcchen** [comment]
@coding-chenkaikai 
请问集群外部的登陆权限是你们自己设置的吗？

由于phxsql的管理员账号是phxbinlogsvr负责监控mysql而使用的。该账号活动范围仅在集群内部。
因此phxsql只负责修改管理员账号对集群内部ip的相应权限。在修改管理员账号密码时，只对集群ip的权限进行相应的修改。

如果想在集群外登陆mysql进行管理员操作，建议使用不同的账号密码。

**Comment by coding-chenkaikai** [comment]
@cjcchen 我没有做任何操作，只是使用提供phxbinlogsvr_tools创建新管理员，然后我看到此管理员拥有所有机器访问权限（集群内，集群外），集群内正常，集群外，密码变为空

**Comment by hzlpy** [comment]
我遇到的情形是这样的。
IPA 是集群中的 master，IPB 是集群外的主机，在 IPA 的数据库中设置允许 IPB 进行远程访问。
在 IPA 主机上连接数据库：
```
root@Vm-template-100G:/home/xxx# mysql -uhappy -hIPA -P54321 -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'happy'@'IPA' (using password: NO)

root@Vm-template-100G:/home/teaj.tang# mysql -uhappy -hIPA -P54321 -p'psw'
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 652982
Server version: 5.6.31-77.0-log Source distribution

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```
在 IPB 主机上连接 IPA 主机的数据库，不需要密码就可以连接成功。如下：
```
root@idreamsky:/home/idreamsky# mysql -uhappy -hIPA -P54321
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 653162
Server version: 5.6.31-77.0-log Source distribution

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
root@idreamsky:/home/idreamsky# mysql -uhappy -hIPA -P54321 -p'psw'
ERROR 1045 (28000): Access denied for user 'happy'@'IPB' (using password: YES)
```

**Comment by cjcchen** [comment]
@coding-chenkaikai 关于修改管理员后，集群外的机器可以不适用密码登陆的问题，我们已经修复了。可以尝试更新代码重新编译。

感谢您的反馈

**Comment by coding-chenkaikai** [comment]
@cjcchen  好的，谢谢

**Comment by coding-chenkaikai** [comment]
我使用最新代码进行编译，设置sqlproxy的端口为19521，集群中主机通过读写端口可以连接上mysql server，但是通过只读端口19522只能连接上master，其余集群内主机均连接不上，我又通过脚本创建管理员用户，出现同样的问题
集群所有主机MasterEnableReadPort = 1，同样提示如下：
```
[root@ip3 phxsql]# mysql -uroot -P19522 -h"ip3"
ERROR 1045 (28000): Access denied for user 'root'@'ip3' (using password: NO)
[root@ip3 phxsql]# 
[root@ip3 phxsql]# mysql -uroot -P19522 -h"ip2"
ERROR 1045 (28000): Access denied for user 'root'@'ip2' (using password: NO)
[root@ip3 phxsql]# 
[root@ip3 phxsql]# mysql -uroot -P19522 -h"ip1"
Welcome to the MySQL monitor.  Commands end with ; or \g.
```

**Comment by cjcchen** [comment]
@coding-chenkaikai  我们这边测试过没有什么异常。麻烦更新下最新代码重新尝试一下。

**Comment by coding-chenkaikai** [comment]
@cjcchen 使用的是最新代码，编译过程没有出现任何错误，执行下面命令没有任何问题，重现编译之后，问题可以重现，只读端口只有Master可以连接
```
./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster
./phxbinlogsvr_tools_phxrpc -f GetMasterInfoFromGlobal
./phxbinlogsvr_tools_phxrpc -f GetMemberList
```

**Comment by cjcchen** [comment]
@coding-chenkaikai 麻烦更新到最新的代码之后，如果可以重新安装一下集群。如果不能安装，可尝试通过工具修改数据同步账号的账号密码为管理员的账号密码。然后再次使用工具修改为正常的数据同步账号的账号密码。

谢谢您的反馈。
