### ISSUE TITLE
部署时出错， python2.7 install.py -i "ip1,ip2,ip3" -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f /tmp/data/

### ISSUE THREAD

**Issue by carlden** [tencent-wechat/phxsql#35]
环境：centos7 
编译过程：
git clone --recursive https://github.com/tencent-wechat/phxsql.git
进入third_party目录。
./autoinstall.sh   =>成功
解压percona至phxsql根目录
./autoinstall.sh
make && make install =>成功

部署：
make  /tmp/data
python2.7 install.py -i "ip1,ip2,ip3" -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f /tmp/data/
报错：
 Namespace(agent_port=6000, base_dir='/data/phxsql/phxsql/install_package/', data_dir='/tmp/data/', inner_ip='ip1', ip_list='ip1,ip2,ip3', module_name='test', mysql_port=11111, paxos_port=8001, phxbinlogsvr_port=17000, phxsqlproxy_port=54321, process_name='all')
kill all binaries success....
mkdir: cannot create directory '/data/phxsql/phxsql/install_package/etc': File exists
generate all configs success....
/tmp/data/phxbinlogsvr
mkdir: cannot create directory '/tmp/data/log': File exists
/tmp/data/percona.workspace
chown: invalid user: 'user:mysql'
cd /data/phxsql/phxsql/install_package/percona.src; ./scripts/mysql_install_db --defaults-file=/data/phxsql/phxsql/install_package/etc/my.cnf --user=mysql
Installing MySQL system tables...2016-09-23 14:16:54 0 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
2016-09-23 14:16:54 0 [Note] ./bin/mysqld (mysqld 5.6.31-77.0-log) starting as process 2116 ...
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......

**Comment by mariohuang** [comment]
请使用root权限重试下？

**Comment by carlden** [comment]
@mariohuang 部署时用的就是root权限

**Comment by mmyyfirstb** [comment]
在directory_operator.py   修改成这个os.system( 'chown mysql:mysql -R %s'%mysql_data_dir )试试

**Comment by carlden** [comment]
@mmyyfirstb 解决

**Comment by jos666** [comment]
新建一个mysql用户就可以了
