### ISSUE TITLE
Master crash多长时间完成Master选举

### ISSUE THREAD

**Issue by coding-chenkaikai** [tencent-wechat/phxsql#37]
成功部署包含5个主机的集群，遇到如下问题：
1、Master crash之后，集群中所有写操作都连接不了，多长时间完成选举？
2、并发数大会导致集群连接不了
`error 2013: Lost connection to MySQL server at 'reading initial communication packet', system error: 0`
3、执行完大量写操作之后，再次进行写操作会Lose connect
`ERROR 2013 (HY000): Lost connection to MySQL server during query`

**Comment by hzlpy** [comment]
@coding-chenkaikai 请问你这个高并发怎么测试的呢？我也想试试。

**Comment by mariohuang** [comment]
能否提供更多的信息，比如：
测试机型
测试时的关键参数（phxsqlproxy配置的线程数，协程数，你测试时的并发访问线程数，连接类型等等）
测试的SQL类型

另外，第二个问题的并发数具体到了什么量级，第三个问题的大量写具体是多大，是一个SQL很大，还是多条小SQL并发执行？

**Comment by hzlpy** [comment]
@mariohuang 请问：
1. master 如果需要切换（如 crash）时，多长时间能完成切换，即感知到 crash 加上选举新的 master 过程要多久？

**Comment by mariohuang** [comment]
@hzlpy 这个取决于配置，在phxbinlogsvr.conf可以配置master的租约长度。

**Comment by coding-chenkaikai** [comment]
@mariohuang ，所有配置保持初始化没变，并发数200，最大连接数10w，问题2、3重新部署之后没有出现，关于问题1，如果直接kill掉phxsqlproxy，集群变得不可用？重新选举master的触发条件是什么？

**Comment by cjcchen** [comment]
重新选择的条件是mysql已经重放完所有数据和phxsqlproxy正常服务。如果两者有一者不正常，则master会被重新选举。
对于kill掉master的phxsqlproxy时集群不可用，这里的不可用应该只是在短时间（租约时间）内的不可用，原master的租约过期后，会重新进行选举。

2016-09-29 17:44 GMT+08:00 coding-chenkaikai <notifications@github.com>:

**Comment by coding-chenkaikai** [comment]
@cjcchen @mariohuang 关于数据库数据的问题，我是这样测试的：
部署一个集群，ip1，ip2，ip3，ip1为Master，现在对数据库创建了一些库，插入了些表，现kill掉ip1的phxsqlproxy，集群进入选举Master，选举完成之后，连接数据库查看，数据库和表都没了？
读写端口是19521
```
[root@ddaeb411d104 sbin]# mysql -uroot -P19521 -h"ip1" -e"select * from agent.user;"
# 有数据，kill掉ip1上的phxsqlproxy，连接ip3
[root@ddaeb411d104 sbin]# mysql -uroot -P19521 -h"ip3" -e"select * from agent.user;"
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2
[root@ddaeb411d104 sbin]# mysql -uroot -P19521 -h"ip3" -e"select * from agent.user;"
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2
[root@ddaeb411d104 sbin]# mysql -uroot -P19521 -h"ip3" -e"select * from agent.user;"
ERROR 1146 (42S02) at line 1: Table 'agent.user' doesn't exist
[root@ddaeb411d104 sbin]# mysql -uroot -P19521 -h"ip3" -e"select * from agent.user;"
ERROR 1146 (42S02) at line 1: Table 'agent.user' doesn't exist
```

**Comment by cjcchen** [comment]
@coding-chenkaikai 请问是否可以进行一下下面几个步骤的确认吗？

1. 集群安装完后，利用工具查看ip1,ip2,ip3是否已经正常加入到集群中。
> 可通过phxbinlogsvr_tools_phxrpc -f GetMemberList -h ip1 -p port1 查看集群机器列表

2. 登陆phxsql，执行一些命令，例如create database test; 并查看另几台机器是否有同步。

3. 操作你想要的命令。

**Comment by coding-chenkaikai** [comment]
@cjcchen 第一步没问题，可以正常显示，第二步，写操作正常，读操作出现以上问题，第三部也出现该问题

**Comment by cjcchen** [comment]
@coding-chenkaikai 如果第二步读操作失败，那就是集群安装的时候出现错误。数据未能同步到其他机器。

是否尝试过更新最新的代码，然后重新安装新的集群？

**Comment by jackdai123** [comment]
@cjcchen 我也遇到与 @coding-chenkaikai 同样的问题，最新的代码、可以重现；

还有，在使用tools/test_phxsql.sh测试时发现只有Master可使用自读端口，错误是ERROR 1045 (28000): Access denied for user 'root'@'192.168.58.10' (using password: NO)

使用tools/test_phxsql.sh测试完以后，停掉Master机，并等选主成功后，登录phxsql，发现测试时创建的test_phxsql数据库和表均丢失了

**Comment by wodesuck** [comment]
@jackdai123 你的情况可能是MySQL插件没有加载成功，到本地MySQL执行show plugins看一下是否有rpl_phx_sync_master，若没有，查一下MySQL日志看是什么原因。

**Comment by jackdai123** [comment]
@wodesuck show plugins确实没有rpl_phx_sync_master，下面是机器上的进程，按照默认配置的，是不是要调整--plugin-load=phxsync_master_phxrpc.so成绝对路径？

[vagrant@localhost log]$ ps -ef | grep phxsql
vagrant   1704  3895  0 08:01 pts/0    00:00:00 grep --color=auto phxsql
vagrant  21787     1  0 07:25 pts/0    00:00:00 sh /home/vagrant/phxsql/bin/mysqld_safe --defaults-file=/home/vagrant/phxsql/etc/my.cnf --super_read_only --plugin-load=phxsync_master_phxrpc.so
vagrant  21789     1  2 07:25 pts/0    00:01:02 /home/vagrant/phxsql/sbin/phxbinlogsvr_phxrpc
vagrant  21795     1  6 07:25 pts/0    00:02:21 /home/vagrant/phxsql/sbin/phxsqlproxy_phxrpc /home/vagrant/phxsql/etc/phxsqlproxy.conf daemon
vagrant  21796     1  6 07:25 pts/0    00:02:21 /home/vagrant/phxsql/sbin/phxsqlproxy_phxrpc /home/vagrant/phxsql/etc/phxsqlproxy.conf daemon
vagrant  23181 21787  1 07:25 pts/0    00:00:24 /home/vagrant/phxsql/sbin/mysqld --defaults-file=/home/vagrant/phxsql/etc/my.cnf --basedir=/home/vagrant/phxsql/percona.src --datadir=/home/vagrant/phxsql/data/percona.workspace/data --plugin-dir=/home/vagrant/phxsql/lib --super-read-only --plugin-load=phxsync_master_phxrpc.so --log-error=/home/vagrant/phxsql/data/percona.workspace/log.err --pid-file=/home/vagrant/phxsql/data/percona.workspace/data/percona.pid --socket=/home/vagrant/phxsql/data/percona.workspace/tmp/percona.sock --port=11111

**Comment by wodesuck** [comment]
看一下`/home/vagrant/phxsql/data/percona.workspace/log.err`，应该有相关的log。

**Comment by jackdai123** [comment]
@wodesuck 找到问题了，是phxsync_master_phxrpc.so缺少依赖，mysql加载so时提示缺少符号，故需改动phxsql/phx_percona/percona/plugin/phxsync_phxrpc/CMakeLists.txt：
在PHXCLIENTLIB_SRC增加libgflags.a依赖
在PHXCLIENTLIB_DIR增加${BASE_PATH}/third_party/gflags/lib（我把gflags放在third_party下）

**Comment by wodesuck** [comment]
@jackdai123 gflags好像是glog的一个可选依赖，可能是你编译环境有这个库所以自动带进来这个依赖吧。Whatever，问题解决了就好。
