### ISSUE TITLE
Comparison between phxsql and MySQL Cluster available?

### ISSUE THREAD

**Issue by raarts** [tencent-wechat/phxsql#38]
Hi,

Is there an english language write-up available on this? Why did you choose to develop this instead of using MySQL Cluster?

Thanks.

**Comment by cjcchen** [comment]
Hi，

There is a small article about a simple introduction and the usage of the PhxSQL in the wiki of GitHub.  You can have a check if you are interested in it.    
  
As is known, MySQL Cluster is a famous distributed system. However, it can not provide strong consistent data, which means some data will be lost in some specific conditions. PhxSQL is developed to improve the data consistency and to keep the Cluster from data lost in these specific circumstance.

Thanks.

**Comment by raarts** [comment]
Thanks, looks good!
