### ISSUE TITLE
phxsql运行相关问题

### ISSUE THREAD

**Issue by mmyyfirstb** [tencent-wechat/phxsql#39]
我们一共是三台服务器
1. 在运行一段时间后，集群出现#HY000The MySQL server is running with the --read-only (super) option so it cannot execute this statement。三台服务器的54321写端口均无法写
2. 如果在运行中phxbinlogsvr出现中断掉线等错误，有什么方法能够监控并给我们告警信息
3. 能否在运行的过程中切换成指定的某台服务器为maseter，而不是集群本身自己选举，或者指定某个服务器申请下一个租约

**Comment by cjcchen** [comment]
1. 该情况通常是master选举不成功，请检查机器间网络是否通畅，mysql是否正常。 如果是使用虚拟机来测试，请确定虚拟机ip是否固定。 如果机器间网络延迟较大，可修改etc/phxbinlogsvr.conf配置中的masterlease选项，增大master的租约时间。
2. 对于默认的phxsql，可以通过开发简单脚本来探测phxsqlproxy，mysql和phxbinlogsvr的二进制是否存在。如不存在，则触发告警。
   也可以修改phxsql的代码。phxsql支持监控插件，在内部做了很多监控的点，而用户只需要实现如何处理这些监控。 
     > 在phxbinlog_server.cpp的InitMonitor函数中注册插件（PhxBinlogStatFactory::SetPhxBinlogStat)。监控插件代码详情可查看phxbinlog_stat.h。

3. 由于master的选举流程稍微复杂，因此外部指定master的功能暂时不支持。

**Comment by mmyyfirstb** [comment]
@cjcchen 谢谢解答~，另外对于第一点：
我们用的是tLinux2.0的三台实体机，在同一机房同一机架上，应该没有太大网络延迟问题。之前我们在三台机器上分别作了容灾，重新部署某一台机器演练。 在一段时间内是没有问题的，但是长时间后就出现这个问题。并且使用phxbinlogsvr_tools_phxrpc -f GetMasterInfoFromGlobal -h ip -p 17000  查看也展示了master机器。
问：是否存在一些其他可能导致该问题？

**Comment by cjcchen** [comment]
@mmyyfirstb 麻烦更新一下代码，再尝试一下是否还有此情况发生。
