### ISSUE TITLE
an error  No such file or directory: '/usr/phxsql//etc/my.cnf'  happened , when executing install.py

### ISSUE THREAD

**Issue by theseusyang** [tencent-wechat/phxsql#4]
when executing this install command line:

`python install.py -i loalhost -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f/tmp/data/`

Namespace(agent_port=6000, base_dir='/usr/phxsql/', data_dir='/tmp/data/', inner_ip='192.168.56.102', ip_list='192.168.56.102', module_name='test', mysql_port=11111, paxos_port=8001, phxbinlogsvr_port=17000, phxsqlproxy_port=54321, process_name='all')
kill all binaries success....
Traceback (most recent call last):
  File "install.py", line 89, in <module>
    generate_config_ret = cg.generate_config()
  File "/usr/phxsql/tools/config_generator.py", line 17, in generate_config
    ret = self.generate_mysql_config()
  File "/usr/phxsql/tools/config_generator.py", line 49, in generate_mysql_config
    cp.write( open( '%s/etc/my.cnf'%self.m_args.base_dir, 'w' ) )
IOError: [Errno 2] No such file or directory: '/usr/phxsql//etc/my.cnf'

**Comment by mariohuang** [comment]
Please make sure you have the permission to create file in /usr/phxsql/etc/

**Comment by theseusyang** [comment]
也就是说 etc/my.cnf 这些文件是在安装的时候在 /usr/phxsql/目录下创建出来的?

**Comment by theseusyang** [comment]
python 的版本是 Python 2.7.6

**Comment by mariohuang** [comment]
是的，我们会根据tools/etc_template/my.cnf的文件生成一份文件放到etc/下，如果执行无法成功，你可以尝试手动复制该文件并修改其中的ip端口等参数。

**Comment by theseusyang** [comment]
好, 我先试下

**Comment by theseusyang** [comment]
config_generator.py 脚本中的 cp.write()中路径有问题,  
cp.write(open('%s/etc/my.cnf' % self.m_args.base_dir,'w'))中.'%s/etc/my.cnf' 显示的是 '/xxx/xxx//etc/my.cnf'的文件路径, 显然这个路径是错误的.

**Comment by mariohuang** [comment]
请问你的安装包放在哪个目录下？
如果是/usr/phxsql，那么我们将会生成/usr/phxsql/etc/my.cnf文件。

**Comment by theseusyang** [comment]
是放在/usr/phxsql目录下, 安装脚本的路径是错的

IOError: [Errno 2] No such file or directory: '/usr/phxsql//etc/my.cnf'

**Comment by theseusyang** [comment]
generate all configs success....
mkdir: cannot create directory ‘/tmp/data//log’: No such file or directory
/tmp/data//phxbinlogsvr
mkdir: cannot create directory ‘/tmp/data//phxbinlogsvr’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//phxbinlogsvr/phxbinlogsvr’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//phxbinlogsvr/phxbinlogsvr/event_data’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//phxbinlogsvr/phxbinlogsvr/paxoslog’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//log’: No such file or directory
/tmp/data//percona.workspace
mkdir: cannot create directory ‘/tmp/data//percona.workspace’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//percona.workspace/data’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//percona.workspace/tmp’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//percona.workspace/binlog’: No such file or directory
mkdir: cannot create directory ‘/tmp/data//percona.workspace/innodb’: No such file or directory
chown: invalid user: ‘user:mysql’
cd /usr/phxsql//percona.src; ./scripts/mysql_install_db --defaults-file=/usr/phxsql//etc/my.cnf --user=mysql
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Use of uninitialized value in chown at ./scripts/mysql_install_db line 700.
Installing MySQL system tables..../bin/mysqld: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./bin/mysqld)
./bin/mysqld: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./bin/mysqld)
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......

**Comment by theseusyang** [comment]
调试了一下, 已经解决目录错误的问题.
 在 install.py中设置路径的时候多了一个"/", 如/tmp/data/, 正确设置方式是 /tmp/data

**Comment by mariohuang** [comment]
好的，谢谢，我们会尽力改善并做好其中的兼容工作:)

**Comment by toontong** [comment]
这个情况算是一个python 脚本 中的bug阿，$BASE_DIR/etc 目录确实没自动创建，都没代码提交，不应该close吧。

**Comment by mariohuang** [comment]
Sorry for the problem. Github ignore the empty directory phxrpc_package_config/etc in our first release. And we fixed it now!

**Comment by hzlpy** [comment]
```
2016-09-01 17:16:54 0 [Note] ./bin/mysqld (mysqld 5.6.31-77.0-log) starting as process 15248 ...
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......
```
出现了这个问题，有人遇到过吗？要怎么解决？

**Comment by mariohuang** [comment]
你好，请把etc/my.cnf中的innodb_buffer_pool_size和innodb_log_file_size调小为你的内存可接受的范围然后再试试

**Comment by hzlpy** [comment]
不行。
而且，经过我的测试，发现改过之后再执行
` sudo python install.py -i localhost -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f/tmp/data/`
改过的两个参数又会被恢复修改之前的默认值。

**Comment by mariohuang** [comment]
你好，请修改tools/etc_template/my.cnf内这两个选项的值。在install时，我们会根据该模版生成最终使用的my.cnf。

**Comment by hzlpy** [comment]
分别改到了 100 M 和 50 M，还是同样的问题。
不修改参数，换一台电脑是可以执行的-_-#。

**Comment by toontong** [comment]
先是取代码使用recurse-submodule选项的，3个phx***又各自有相同的submodule，取了不少时间。
再试在在centos-7下试编译，又各种问题，最终放弃。

改用docker吧，上传的 bin文件使用的是gcc4.8编译的， 我想制作一个Dockerfile，发现各种坑。
hub.docker.io使用的镜像并不是4.8。解决了4.8问题，还有install.py脚本的bug。
docker pull gcc:4.8后，又莫名发现mysql_install_db有perl的语法错~ 直了~又是镜像问题。
好吧，我暂时放弃了跑phxsql起来。
#8

**Comment by hzlpy** [comment]
目前，执行时不带 sudo 会避免该错误，还在探索后面的步骤。

**Comment by fushengyxx** [comment]
我用python2.7 install.py -i IP -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f/tmp/data/ -s1会报错
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......
如果不加最后的-s1就可以正常启动phxsql。请问要怎么解决才能保留迁移过来的数据

**Comment by wodesuck** [comment]
@fushengyxx 麻烦贴一下详细日志。

**Comment by zhgypg** [comment]
碰到类似的问题，不知道作者还在维护这个代码吗？

[root@phx02 tools]# python2.7 install.py -i "192.168.1.56" -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f /home/phxsql/data/
Namespace(agent_port=6000, base_dir='/home/phxsql/', data_dir='/home/phxsql/data/', inner_ip='192.168.1.56', ip_list='192.168.1.56', module_name='test', mysql_port=11111, paxos_port=8001, phxbinlogsvr_port=17000, phxsqlproxy_port=54321, process_name='all', skip_data=0)
kill all binaries success....
mkdir: cannot create directory ‘/home/phxsql/etc’: File exists
generate all configs success....
mkdir: cannot create directory ‘/home/phxsql/data/log’: File exists
/home/phxsql/data/phxbinlogsvr
skip data 0
mkdir: cannot create directory ‘/home/phxsql/data/log’: File exists
/home/phxsql/data/percona.workspace
cd /home/phxsql/percona.src; ./scripts/mysql_install_db --defaults-file=/home/phxsql/etc/my.cnf --user=mysql --rpl_phx_sync_master=OFF
Installing MySQL system tables...2020-01-09 17:07:21 0 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
2020-01-09 17:07:21 0 [Note] ./bin/mysqld (mysqld 5.6.31-77.0-log) starting as process 28784 ...
FATAL ERROR: Error closing mysqld pipe: Broken pipe
install mysql failed, ret 256
install failed, exit......
