### ISSUE TITLE
这么大的c++工程，用什么IDE

### ISSUE THREAD

**Issue by liaobinxu** [tencent-wechat/phxsql#43]
请求这么大的c++工程，用什么IDE？

**Comment by cjcchen** [comment]
你好，代码都是在linux开发和编译的。使用windows的IDE可能不太适合。

**Comment by liaobinxu** [comment]
对make file支持较好，带代码提示的IDE哪些？这个项目很多makefile还是用Python工具程序生成的？

**Comment by liaobinxu** [comment]
你们用的是Emacs还是vim ?

**Comment by lynncui00** [comment]
@liaobinxu  我们用的vim.

**Comment by TigerZhang** [comment]
@liaobinxu 推荐用 CLion，支持 CMake
