### ISSUE TITLE
PHXSQL 的一些参数问题

### ISSUE THREAD

**Issue by wedonot** [tencent-wechat/phxsql#44]
innodb_support_xa = 0 在默认配置中是关闭的，但是关闭了这个参数，就无法2pc保证binlog和redo一致性，请问我们为了保证高可用性，是否应该打开这个参数？或者说在你们的架构中是有其他的方式来保证binlog和redo的一致性？

**Comment by wodesuck** [comment]
应该是1，默认配置有问题，已fix (6c0d50636344cead4c78662129b1565af3be6e9e)
