### ISSUE TITLE
关于binlog的全局顺序

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#45]
现在测试中遇到一个问题，环境是3台PhxSQL的集群，在一些测试用例密集运行时，模拟3台机器轮流出现单点故障（主要是kill phxsqlproxy或者phxbinlogsvr，下一台PhxSQL的角色被kill前会恢复前一台的所有服务），结果在大概两轮过后，发现一台PhxSQL服务重动后流水不能自动追上，错误消息是：binlog的写入不能符合某个外键约束。

重新安装问题机器，机器开始追流水，但追了没多久就又开始出现同样的问题。测试用例中大概是插入一些数据，更改、查询后删除之。

我想问的是，每台机器上的binlog是有顺序的，但全局是否有序？

**Comment by cjcchen** [comment]
请问在出问题的机器上，mysql的gtid顺序是连续的吗？
查看mysql的gtid的执行状态，可通过show slave status\G;查看executed gtid list;

**Comment by zqdai** [comment]
查看过，是连续的噢。大概的样子是：
executed gtid list：M1:1-T1, 
M2: 1-T2,
M3:1-T3

反复执行show slave status还可以看到新取回来一些（Retrieved GTID List），例如M2: T2+1 - T2+n，但执行出错了。

**Comment by cjcchen** [comment]
可以尝试一下把mysql的配置参数innodb_support_xa 设置为1（innodb_support_xa=1）。
从表现上看，可能是master和slave在binlog上的执行顺序不太一样，导致一些binlog的执行结果被跳过。

在正常情况下，1-T2的binlog已经执行完，第T2+1条binlog应该不会出现执行失败。这里能否查看一下这条binlog执行失败的原因吗？能否查看下是否有某条binlog执行成功但其实是失败的情况？ binlog的执行语句可通过show binlog events语句查看。

另外：
binlog是全局有序的，按照master提交的顺序保存在phxbinlogsvr，并按照顺序下发给slave。

**Comment by zqdai** [comment]
@cjcchen 谢谢！

环境已经重装了，暂时不好查看。该问题出现于 kill mysqld_safe 和 mysqld之后。跟innodb_support_xa有关的可能性较大。。

thanks again!
