### ISSUE TITLE
系统产生大量“Too many open files” 

### ISSUE THREAD

**Issue by xrootman** [tencent-wechat/phxsql#47]
在那个PHXBINLOGSVR在两个从被杀之后，主执行DML，然后MYSQLD重启,在BEFORE RECOVERY阶段循环调用GET LAST GTID，导致大量的CLOSE WAIT TCP SOCKET文件的出现，直到TOO MANY FILES被断言退出的情况，基本可以确定不是有意这样设计的。
情景描述：系统产生大量“Too many open files” 
原因分析：在服务器与客户端通信过程中，因服务器发生了socket未关导致的closed_wait发生，致使监听port打开的句柄数到了1024个，且均处于close_wait的状态，最终造成配置的port被占满出现“Too many open files”，无法再进行通信。 
close_wait状态出现的原因是被动关闭方未关闭socket造成，如附件图所示： 

解决办法：有两种措施可行 
一、解决： 
原因是因为调用ServerSocket类的accept()方法和Socket输入流的read()方法时会引起线程阻塞，所以应该用setSoTimeout()方法设置超时（缺省的设置是0，即超时永远不会发生）；超时的判断是累计式的，一次设置后，每次调用引起的阻塞时间都从该值中扣除，直至另一次超时设置或有超时异常抛出。 
比如，某种服务需要三次调用read()，超时设置为1分钟，那么如果某次服务三次read()调用的总时间超过1分钟就会有异常抛出，如果要在同一个Socket上反复进行这种服务，就要在每次服务之前设置一次超时。 

动关闭方未关闭socket造成大量closed_wait的TCP端口文件，最终因为进程打开太多文件“Too many open files”，被RPC框架的断言干掉

端口会快速地增长[root@bssmysql025~]# lsof|grep 5845|grep TCP|grep CLOSE_WAIT>cyg.tcpsocket.log1[root@bssmysql025~]# lsof|grep 5845|grep TCP|grep CLOSE_WAIT>cyg.tcpsocket.log2不到2分钟的时间，已经从630个增长到5664个

**Comment by xrootman** [comment]
这个问题需要修复。

**Comment by xrootman** [comment]
补充：
第一、关于TOO MANY FILES的问题，其实正常规范操作下不会发生的。这个异常触发的场景是一主两从，两从的BINLOGSVR CRASH了，主的状态在20秒之后EXPIRE之后，主的MYSQL上有DML操作。正常状态下所有的MYSQL操作都要经过PROXY中转，而那个时候PROXY是无法连上的，所以正常状态下不会触发，除非有直连MYSQL写数据的情况。不过为了应付各种异常，还是应该提。
第二、 AgentMonitor::Process()函数有个小问题。按代码的意思，应该是上次检查和这次检查的时间间隔超过CheckStatusPeriod周期，才去执行一次CheckMasterTimeOut。但实际上这个CheckStatusPeriod参数没起到任何作用，因为LAST CHECK=0写到循环里面去了，每次都会是0，而不是期望中的  last_check = now;应该把这句放到循环体外。

**Comment by cjcchen** [comment]
@xrootman 请问这个TOO MANY FILES是出现在mysql还是phxbinlogsvr呢？
能否贴一下相关日志信息?

**Comment by xrootman** [comment]
这句是日志E1008 14:25:05.847457 59581 phx_glog.cpp:82] ERR: epoll_create( 300 ) -1, errno 24, Too many open files

**Comment by xrootman** [comment]
这里好像不能上传图片，要不您提供QQ或是邮件地址 我将相关的图片发给您？

**Comment by xrootman** [comment]
上面提到TOO MANY FILES的问题正常情况下不会出现，因为MASTER在两从的BINLOGSVR死掉后会EXPIRE,从而导致PROXY的54321读写商品连不上而无法对MYSQL进行DML。但实际上，连两个从的54321是连不上，连主的54321还是可以连上的。这是一个异常。
分析了日志和代码，发现问题主要在这里。
正常的逻辑下
这里应该因为EXPIRE从而  return -__LINE__;的，从而导致 连PROXY失败，但是实际上却成功了，没有EXPIRE,见日志，问题出在了GET MASTER函数的DECODE MASTER函数的逻辑上

只有UPDATE TIME为0的时候才会直接返回EXPIRE TIME，不为0的时候返回的都是当前时间+租约时间，换言之主库状态变成永不过期服。


 可以做一个相对简单的实验，
把两个从库的BINLOGSVR杀死，再用./phxbinlogsvr_tools_phxrpc -f GetMemberList -h 192.168.65.93 -p 17000去看主库的状态，发现EXPIRETIME一直在更新，实际上主库的状态一早就因为失去过半集群无法更新了（我GDB看过内存状态也确认了这一点），但返回的时候居然让DECODE函数主动加上了，
所以可以很容易发现，即使两从BINLOGSVR都死了，取主状态的EXPIRETIME也一直正常和两从活的时候一致。
这个BUG会导致我前文提的TOO MANY FILES变成了正常情况下也会触发了，本来应该是有异常操作才会触发的。

**Comment by xrootman** [comment]
上面的内容中一些图片  我已直接邮件回复给你们了。

**Comment by lynncui00** [comment]
@xrootman 邮件发到什么邮箱了？phxteam没收到。

**Comment by xrootman** [comment]
我是直接回复全部。你们的邮箱是多少呢？

**Comment by wodesuck** [comment]
@xrootman 尝试重现你的实验失败，杀掉两从的binlogsvr后，GetMemberList返回"get master fail ret -1"。请问是否还有别的触发条件？

**Comment by xrootman** [comment]
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008    
get master 192.168.65.88 expire time 1476408197
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008


杀掉两个从库的phxbinlogsvr_phxrpc
[apps@db1n14 ~]$ ps -ef | grep phxsql
apps     24923 24866  0 09:22 pts/154  00:00:00 /apps/soft/pz/phxsql//percona.src/bin/mysql -uroot -p -h192.168.65.89 -P54328
apps     24925 24866  0 09:22 pts/154  00:00:00 /apps/soft/pz/phxsql//percona.src/bin/mysql -uroot -p -h192.168.65.89 -P54329
apps     25034 24866  0 09:24 pts/154  00:00:00 grep phxsql
apps     26548     1 10 Oct10 ?        09:41:55 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     26549     1 10 Oct10 ?        09:46:48 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     26619     1  1 Oct10 ?        01:54:35 /apps/soft/pz/phxsql//sbin/phxbinlogsvr_phxrpc
apps     26743     1  0 Oct10 ?        00:00:00 sh /apps/soft/pz/phxsql//bin/mysqld_safe --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --super_read_only --plugin-

load=phxsync_master_phxrpc.so
apps     27950 26743  0 Oct10 ?        00:18:00 /apps/soft/pz/phxsql/sbin/mysqld --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --

basedir=/apps/soft/pz/phxsql//percona.src --datadir=/apps/soft/pz/data/percona.workspace/data --plugin-dir=/apps/soft/pz/phxsql//lib --super-read-only --plugin-

load=phxsync_master_phxrpc.so --log-error=/apps/soft/pz/data/percona.workspace/log.err --pid-file=/apps/soft/pz/data/percona.workspace/data/percona.pid --

socket=/apps/soft/pz/data/percona.workspace/tmp/percona.sock --port=11118
[apps@db1n14 ~]$ kill -9  26619 
[apps@db1n14 ~]$ ps -ef | grep phxsql
apps     24923 24866  0 09:22 pts/154  00:00:00 /apps/soft/pz/phxsql//percona.src/bin/mysql -uroot -p -h192.168.65.89 -P54328
apps     24925 24866  0 09:22 pts/154  00:00:00 /apps/soft/pz/phxsql//percona.src/bin/mysql -uroot -p -h192.168.65.89 -P54329
apps     25040 24866  0 09:26 pts/154  00:00:00 grep phxsql
apps     26548     1 10 Oct10 ?        09:42:08 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     26549     1 10 Oct10 ?        09:47:01 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     26743     1  0 Oct10 ?        00:00:00 sh /apps/soft/pz/phxsql//bin/mysqld_safe --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --super_read_only --plugin-

load=phxsync_master_phxrpc.so
apps     27950 26743  0 Oct10 ?        00:18:00 /apps/soft/pz/phxsql/sbin/mysqld --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --

basedir=/apps/soft/pz/phxsql//percona.src --datadir=/apps/soft/pz/data/percona.workspace/data --plugin-dir=/apps/soft/pz/phxsql//lib --super-read-only --plugin-

load=phxsync_master_phxrpc.so --log-error=/apps/soft/pz/data/percona.workspace/log.err --pid-file=/apps/soft/pz/data/percona.workspace/data/percona.pid --

socket=/apps/soft/pz/data/percona.workspace/tmp/percona.sock --port=11118


[root@db1n15 ~]# ps -ef | grep phxsql
root     33495 30414  0 09:24 pts/155  00:00:00 grep phxsql
apps     56915     1  0 Oct08 ?        00:00:00 sh /apps/soft/pz/phxsql//bin/mysqld_safe --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --super_read_only --plugin-

load=phxsync_master_phxrpc.so
apps     56918     1 20 Oct08 ?        1-05:11:22 /apps/soft/pz/phxsql//sbin/phxbinlogsvr_phxrpc
apps     56935     1 18 Oct08 ?        1-03:05:04 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     56936     1 18 Oct08 ?        1-03:07:24 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     58396 56915  2 Oct08 ?        03:29:52 /apps/soft/pz/phxsql/sbin/mysqld --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --

basedir=/apps/soft/pz/phxsql//percona.src --datadir=/apps/soft/pz/data/percona.workspace/data --plugin-dir=/apps/soft/pz/phxsql//lib --super-read-only --plugin-

load=phxsync_master_phxrpc.so --log-error=/apps/soft/pz/data/percona.workspace/log.err --pid-file=/apps/soft/pz/data/percona.workspace/data/percona.pid --

socket=/apps/soft/pz/data/percona.workspace/tmp/percona.sock --port=11118
[root@db1n15 ~]# kill -9   56918
[root@db1n15 ~]# 
[root@db1n15 ~]# ps -ef | grep phxsql
root     34270 30414  0 09:26 pts/155  00:00:00 grep phxsql
apps     56915     1  0 Oct08 ?        00:00:00 sh /apps/soft/pz/phxsql//bin/mysqld_safe --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --super_read_only --plugin-

load=phxsync_master_phxrpc.so
apps     56935     1 18 Oct08 ?        1-03:05:31 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     56936     1 18 Oct08 ?        1-03:07:51 /apps/soft/pz/phxsql//sbin/phxsqlproxy_phxrpc /apps/soft/pz/phxsql//etc/phxsqlproxy.conf daemon
apps     58396 56915  2 Oct08 ?        03:29:52 /apps/soft/pz/phxsql/sbin/mysqld --defaults-file=/apps/soft/pz/phxsql//etc/my.cnf --

basedir=/apps/soft/pz/phxsql//percona.src --datadir=/apps/soft/pz/data/percona.workspace/data --plugin-dir=/apps/soft/pz/phxsql//lib --super-read-only --plugin-

load=phxsync_master_phxrpc.so --log-error=/apps/soft/pz/data/percona.workspace/log.err --pid-file=/apps/soft/pz/data/percona.workspace/data/percona.pid --

socket=/apps/soft/pz/data/percona.workspace/tmp/percona.sock --port=11118

查看 ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList 的刷新





[root@db1n13 sbin]# date
Fri Oct 14 09:24:21 CST 2016
[root@db1n13 sbin]# 
[root@db1n13 sbin]# date
Fri Oct 14 09:25:11 CST 2016
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408330
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008



--------------------------kill掉binlogserv 之后的信息---------------------------------------------------
[root@db1n13 sbin]# 
[root@db1n13 sbin]# 
[root@db1n13 sbin]# 
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408397
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408398
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408399
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008


-------------有短时间报get master fail ret -1错误----------------------
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master fail ret -1

Usage: ./phxbinlogsvr_tools_phxrpc [-c <config>] [-f <func>] [-v]
    -f PHXEcho -s <string>
    -f GetMasterInfoFromGlobal -h <host> -p <port>
    -f GetLastSendGtidFromGlobal -h <host> -p <port> -u<gtid>
    -f SetExportIP -h <host> -p <port>
    -f AddMember -h <host> -p <port> -m <member ip>
    -f RemoveMember -h <host> -p <port> -m <member ip>
    -f SetMySqlAdminInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new admin username> -D <new admin pwd>
    -f SetMySqlReplicaInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new replica username> -D <new replica pwd>
    -f GetMemberList -h <host> -p <port>
    -f InitBinlogSvrMaster -h <ip1,ip2,ip3(ip1 is master, others are slaves)> -p <port>

[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408405
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408548
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008
[root@db1n13 sbin]# ./phxbinlogsvr_tools_phxrpc  -f    GetMemberList -h192.168.65.88 -p 17008
get master 192.168.65.88 expire time 1476408549
ip 192.168.65.88 port 17008
ip 192.168.65.90 port 17008
ip 192.168.65.89 port 17008

**Comment by xrootman** [comment]
补充：
杀了两个从之后，主的状态已经不再更新了。但我们用这个命令看的时候会发现EXPIRETIME还是在不断地增长。有某些时候也会得到-1。
问题出在了GET MASTER函数的DECODE MASTER函数的逻辑上，只有UPDATE TIME为0的时候才会直接返回EXPIRE TIME，不为0的时候返回的都是当前时间+租约时间，换言之主库状态变成永不过期服。

**Comment by CYGWING** [comment]
相关的代码
bool PhxBinlogClient::DecodeMasterInfo(const string &decode_buffer, string *ip, uint32_t *expire_time,
                                       uint32_t *version) {
    phxbinlogsvr::MasterInfo master_info;
    if (!master_info.ParseFromString(decode_buffer)) {
        ColorLogError("%s master fail", __func__);
        return false;
    }

    LogVerbose("%s master ip %s, update time %u expire time %u", __func__, master_info.ip().c_str(),
               master_info.update_time(), master_info.expire_time());

    *ip = master_info.ip();
    if (master_info.update_time() == 0) {
        *expire_time = master_info.expire_time();
    } else {
        uint32_t delta_time = master_info.expire_time() - master_info.update_time();
        *expire_time = time(NULL) + delta_time;
    }
    *version = master_info.version();
    return true;
只有UPDATE TIME为0的时候才会直接返回EXPIRE TIME，不为0的时候返回的都是当前时间+租约时间，换言之主库状态变成永不过期.

**Comment by cjcchen** [comment]
@xrootman 你提到的too many open files是指phxsqlproxy连接mysql的时候吗？
