### ISSUE TITLE
编译时最后一步make && make install时出现问题

### ISSUE THREAD

**Issue by liulinjun10086** [tencent-wechat/phxsql#48]
/opt/phxsql/percona/include/mysql.h:71:27: fatal error: mysql_version.h: No such file or directory
 #include "mysql_version.h"
                           ^
compilation terminated.
make[3]: **\* [mysql_command.o] Error 1
make[3]: Leaving directory `/opt/phxsql/phxbinlogsvr/core/mysql'

**Comment by lynncui00** [comment]
请检查 根目录下 `./autoinstall.sh` 这一步是否成功了？

**Comment by LiuLinDeveloper** [comment]
肯定成功了，我才会执行到最后一步啊。前面都显示正常，最后一步报这个错，是为什么

**Comment by cjcchen** [comment]
这个错是安装percona的时候失败了或者autoinstall的时候出现失败导致percona目录的mysql_version.h文件找不到。

可以尝试重新安装。安装前请确保percona目录放到了源代码目录下。

**Comment by toontong** [comment]
贴个编译用的Dockerfile，编译环境：[Dockerfile](https://gist.github.com/toontong/146e98542b2bbcbeca512fba3a03c292)

**Comment by ZHRichardson** [comment]
> 肯定成功了，我才会执行到最后一步啊。前面都显示正常，最后一步报这个错，是为什么

我也遇到和你同样的错误。你是怎么解决的呢？
