### ISSUE TITLE
 phxbinlogsvr日志里大量的 ERROR: httpcall -303

### ISSUE THREAD

**Issue by soniazhai** [tencent-wechat/phxsql#49]
这个错误是什么意思？如何解决？看起来进程都还在正常运行。
另，phxbinlogsvr和phxsqlproxy日志的级别该如何调整？现在日志量太大了

**Comment by cjcchen** [comment]
可以通过配置etc/phxbinlogsvr.conf中的loglevel选项。
级别1<2<3。
目前的级别为3，可以通过降低级别来减少日志。

**Comment by soniazhai** [comment]
thanks @cjcchen

**Comment by soniazhai** [comment]
日志级别调整并重启二进制后（分别尝试了2和1），日志文件还是很大
比如phxsqlproxy.INFO里面都是此类信息
W1011 16:36:39.435902 25662 phx_glog.cpp:78] UpdateGroupStatus:95 GetMaster success but (10.5.77.18:1476131826) expired
W1011 16:36:39.435917 25662 phx_glog.cpp:78] UpdateGroupStatus ret -97

**Comment by cjcchen** [comment]
proxy的日志是通过配置etc/phxsqlproxy.conf中的日志级别。
phxbinlogsvr的日志是通过配置etc/phxbinlogsvr.conf中的日志级别。

配置更新后需要重新启动相应的二进制。

日志级别分为0，1，2，3，如果实在太多，可尝试改成0.

谢谢您的反馈。
