### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by carroarmato0** [tencent-wechat/phxsql#5]
Dit project ziet er heel cool en belovend uit.
Jammer genoeg begrijp ik er niets van, net zoals de meeste mensen niets zullen begrijpen van wat ik hier schrijf, omdat de voertaal niet in het Engels is.

Moest dit in het Engels zijn, zou dit de gemeenschap meer dienst doen, en zouden er ook meer potentiële gebruikers kunnen mee helpen.

**Comment by theseusyang** [comment]
Hi @carroarmato0 :
at best write here english to describe your questions, we cant recognize in Dutch, hahaha

**Comment by ghosty-be** [comment]
Thats just his point ... the rest of the world doesn't get the Chinese either ;)

**Comment by theseusyang** [comment]
Ok @carroarmato0 you win, we can pull some Guys to write documents in english version to make another hemisphere's people convenient.

**Comment by carroarmato0** [comment]
@theseusyang well, I got excited about the project when it appeared in my news feed, but then I realized I can't read Chinese. Probably other people would also be very interested in giving this project a try and maybe help out too. Will only increase the attention the project might get :)

**Comment by mariohuang** [comment]
Hi, all, 
We are doing the translation now and we will post it asap.

**Comment by mariohuang** [comment]
@carroarmato0 @theseusyang @ghosty-be Hi, guys, the English README has been post and we are translating the principle articles to help users in understanding the architecture.
