### ISSUE TITLE
错误 ERROR 2013 (HY000): Lost connection to MySQL server at .. 的原因分析

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#50]
经过测试，这个著名的错误（很多人都遇到的）：
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
应该是phxsqlproxy中的一个bug导致的。导致该错误的直接调用栈：
IORoutine::ConnectDest()
    MasterIORoutine::GetDestEndpoint()
           MasterCache::GetMaster()
                  MasterCache::IsMasterValid()

日志里的错误记录：
W1010 19:15:54.939769  5784 phx_glog.cpp:78] get master [172.16.1.57] expiretime [1476098154] current [1476098154939]
W1010 19:15:54.940032  5784 phx_glog.cpp:78] GetDestEndpoint:599 requniqid 2199472141737567413 getmaster failed, ret -65
W1010 19:15:54.940155  5784 phx_glog.cpp:78] requniqid 2199472141737567413 get mysql ip port failed

可以看到，此时 master 的 expiretime 比当前时间早了N毫秒但小于1秒（实际上是在master正好要过期的时候）。IsMasterValid() 此时返回 false。导致ConnectDest()认为此时不能找到mysql的ip和port。然后连接就断开了。

跟同事讨论了一下，应该是master信息没有及时被update。代码方面还不是很熟，得进一步细看看，希望作者可以帮忙研究下：）

**Comment by cjcchen** [comment]
@zqdai 从日志看，是获取master信息失败了。是否确认下当时是master续租失败还是master存在但是是获取master信息失败呢？

获取master信息可以通过tools查询
> phxbinlogsvr_tools -f GetMasterInfoFromGlobal -h <host> -p <port>

**Comment by wodesuck** [comment]
之前的代码的确会在最后一秒判断过期有问题（proxy跟binlogsvr判断的方式有出入），已fix。
但是正常情况在最后一秒之前master就应该续租好，所以应该master续租失败或者获取master失败才会触发。

**Comment by zqdai** [comment]
@cjcchen 获取的信息实际上是成功的，判定的逻辑有点问题。Daniel（@wodesuck）说的是对的。

谢谢！

**Comment by cjcchen** [comment]
@zqdai 这个问题正常情况下是不会发生的。发生的前提就是master租约续租失败了，导致一致获取到了相同的租约。

因此需要看看phxbinlogsvr为什么续租失败了。是网络问题还是mysql访问失败了。

**Comment by zqdai** [comment]
@cjcchen 嗯好的，我们同事也是这么说的，我再深入跟踪一下。

**Comment by zqdai** [comment]
@cjcchen 讨论中可能忘记了区分一个问题，即这里提到的master信息的其实有两份：phxbinlogsvr中的，和phxsqlproxy中的。前者我想应该是遵守你所提到的续租协议的，然而后者恐怕不是（看代码像是简单的定期更新，或master过期时被动更新？）。在测试中也只发现phxsqlproxy出现问题，而phxbinlogsvr始终正常工作。因此我想问题应该就出在phxsqlproxy的这段的master信息更新逻辑。

**Comment by cjcchen** [comment]
@zqdai 如果能使用工具通过phxbinlogsvr获取到master信息，那么说明master已经续租成功。
如果此时phxsqlproxy出现master失败，那么说明phxsqlproxy向phxbinlogsvr获取master信息的时候，请求失败了。

从之前提供的日志情况来看，应该是属于这种情况。
> W1010 19:15:54.939769 5784 phx_glog.cpp:78] get master [172.16.1.57] expiretime [1476098154] current [1476098154939]
> W1010 19:15:54.940032 5784 phx_glog.cpp:78] GetDestEndpoint:599 requniqid 2199472141737567413 getmaster failed, ret -65
> W1010 19:15:54.940155 5784 phx_glog.cpp:78] requniqid 2199472141737567413 get mysql ip port failed

如果是这种情况，需要提供日志才能确认问题。

**Comment by zqdai** [comment]
以下是出错前后的一段日志，似乎的确发生了读写错误。

I1010 20:57:23.929711  5835 phx_glog.cpp:74] run: 0 IORoutine is working....
I1010 20:57:23.931466  5842 phx_glog.cpp:74] run: 0 IORoutine is working....
I1010 20:57:23.934070  5841 phx_glog.cpp:74] run: 0 IORoutine is working....
W1010 20:57:24.032604  5827 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6411367473070565691 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.049187  5817 phx_glog.cpp:78] TransMsgDirect:344 requniqid 8369900794894922670 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.065464  5804 phx_glog.cpp:78] TransMsgDirect:344 requniqid 278264729302116239 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.216516  5810 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3257968588074460477 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.331328  5815 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6977755633889991547 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.539681  5806 phx_glog.cpp:78] TransMsgDirect:344 requniqid 4659019587596397104 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.554885  5791 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6689224990634892397 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.569898  5796 phx_glog.cpp:78] TransMsgDirect:344 requniqid 290208635561881073 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.751197  5804 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6539753636097564292 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:24.904773  5810 phx_glog.cpp:78] TransMsgDirect:344 requniqid 1097088978750162746 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.071195  5810 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5894712468637358467 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.087899  5837 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3398253227166882834 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.103682  5839 phx_glog.cpp:78] TransMsgDirect:344 requniqid 448593477982902125 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.279671  5817 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3080974174390161342 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.414310  5789 phx_glog.cpp:78] TransMsgDirect:344 requniqid 8698720961732261450 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.589352  5815 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5669174338579390020 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.605046  5801 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2844130407070006685 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.621075  5815 phx_glog.cpp:78] TransMsgDirect:344 requniqid 874814993660683696 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.814286  5801 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3479537201482219278 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:25.958964  5810 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2807237324704097514 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.104192  5793 phx_glog.cpp:78] get master [172.16.1.58] expiretime [1476104246] current [1476104246104]
W1010 20:57:26.104439  5793 phx_glog.cpp:78] CanExecute:551 requniqid 4987482501951032447 getmaster failed, ret -65
W1010 20:57:26.104704  5793 phx_glog.cpp:78] requniqid 4987482501951032447 request [cmd:1] can't execute here
W1010 20:57:26.115667  5842 phx_glog.cpp:78] get master [172.16.1.58] expiretime [1476104246] current [1476104246115]
W1010 20:57:26.115901  5842 phx_glog.cpp:78] GetDestEndpoint:526 requniqid 1181060700429897325 getmaster failed, ret -65
W1010 20:57:26.116037  5842 phx_glog.cpp:78] requniqid 1181060700429897325 get mysql ip port failed
W1010 20:57:26.371685  5833 phx_glog.cpp:78] TransMsgDirect:344 requniqid 8552581984428383456 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.513954  5827 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2224675267368769831 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.722959  5791 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6482024447676895455 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.738412  5806 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3669321167288824285 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.754850  5808 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3166444184094307868 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:26.923250  5806 phx_glog.cpp:78] TransMsgDirect:344 requniqid 7323951253405936037 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.090243  5785 phx_glog.cpp:78] TransMsgDirect:344 requniqid 1936766415404746550 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.307585  5799 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2008667148687576275 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.322897  5819 phx_glog.cpp:78] TransMsgDirect:344 requniqid 724234880387181126 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.337760  5792 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5442820661907491168 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.516280  5791 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3015298726358311511 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.658397  5839 phx_glog.cpp:78] TransMsgDirect:344 requniqid 7557709525621365582 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.825291  5835 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5297238473457773785 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.839941  5817 phx_glog.cpp:78] TransMsgDirect:344 requniqid 1085660255833552762 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:27.855195  5837 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2222666007233107621 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.013463  5810 phx_glog.cpp:78] TransMsgDirect:344 requniqid 824078108079545361 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.220522  5792 phx_glog.cpp:78] TransMsgDirect:344 requniqid 636989740868278773 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.395548  5782 phx_glog.cpp:78] TransMsgDirect:344 requniqid 4737457007510126988 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.409749  5841 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3125000192407586000 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.424798  5827 phx_glog.cpp:78] TransMsgDirect:344 requniqid 9071041453417769997 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.596669  5821 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3770961031928831715 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:28.907613  5839 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6064284816930296361 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.188112  5835 phx_glog.cpp:78] TransMsgDirect:344 requniqid 7699360360502112121 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.203795  5839 phx_glog.cpp:78] TransMsgDirect:344 requniqid 9080784259781928023 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.218750  5833 phx_glog.cpp:78] TransMsgDirect:344 requniqid 8156959193931186716 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.404644  5799 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5758606758882556183 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.545259  5787 phx_glog.cpp:78] TransMsgDirect:344 requniqid 996617031957364503 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.737336  5806 phx_glog.cpp:78] TransMsgDirect:344 requniqid 9572959070304435 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.752929  5801 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6291824358040487190 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.766494  5815 phx_glog.cpp:78] TransMsgDirect:344 requniqid 1740830986533924013 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:29.937677  5831 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2889724714910254440 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.082443  5819 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5832897599278929790 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.313802  5827 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3989281804127756107 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.328960  5823 phx_glog.cpp:78] TransMsgDirect:344 requniqid 6682721143452443776 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.342993  5787 phx_glog.cpp:78] TransMsgDirect:344 requniqid 152814924499333825 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.522719  5833 phx_glog.cpp:78] TransMsgDirect:344 requniqid 991701484928674856 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.647969  5806 phx_glog.cpp:78] TransMsgDirect:344 requniqid 2931980196598429834 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.806663  5799 phx_glog.cpp:78] TransMsgDirect:344 requniqid 1777121467597729519 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.821432  5842 phx_glog.cpp:78] TransMsgDirect:344 requniqid 5437921564667916011 clientfd 26 svrfd 28 source 26 dest 28 read failed, ret 0, errno (0:Success)
W1010 20:57:30.836146  5785 phx_glog.cpp:78] TransMsgDirect:344 requniqid 3998294506144228354 clientfd 27 svrfd 28 source 27 dest 28 read failed, ret 0, errno (0:Success)

**Comment by zqdai** [comment]
经过测试，造成这个issue的一个主要原因应该就是 phxsql master cache 的更新协议导致的。

测试时 master lease 设定为 10s。

按照我们的测试中对binlogsvr和sqlproxy中master expire time的观测，发现
1、binlogsvr 每秒续租。
2、sqlproxy 每隔10秒续租。在这种情况下，存储在sqlproxy中的master信息发生过期的概率很大（主要是相等的情况）。
3、如果调整sqlproxy 每隔10秒以上续租，可以非常明显的观测到更多的连接断开现象。
4、如果调整sqlproxy 每隔3秒续租，则未观测到连接断开现象。

跟我们比较了解paxos的同事讨论了一下，我们认为sqlproxy对master cache的更新间隔是错误的，应该严格小于lease，实际上最好在lease的一半以下。

另外，在更新间隔10秒（当前代码中的值）、lease为20秒的情况下，在某些情况下还是存在连接断开的问题的。

下图是我们实验中观测到的expire time（每秒观测依一次）。值得注意的是 binlogsvr 的尾端有一个“脉冲”，在测试中可以普通观测到，似乎也是不正常的。

![55error](https://cloud.githubusercontent.com/assets/22090539/19349134/11fae5ce-9184-11e6-9900-b1f0028c9036.png)

**Comment by wodesuck** [comment]
实际上proxy是在master过期前10s开始GetMaster，失败的话会每100ms重试一次，成功的话就会sleep 10s，所以租约低于10s的时候会出问题。（这个10s写死在代码里，确实不好，我准备改一下吧…）

**Comment by cjcchen** [comment]
@zqdai 这个确实是我们的一个bug，我们会尽快修复。

对于实验，可以先把租约设置为>10s进行。

谢谢你们的反馈。

**Comment by lynncui00** [comment]
@zqdai 脉冲是实际观测到expire time的倒退现象？实验的过程中系统时间有无进行过修改？

**Comment by cjcchen** [comment]
@zqdai 在尾端部分，是否有对系统做过任何操作呢？ 
另外是否这个脉冲必定存在于尾端，而不视乎实验的时间长短？

**Comment by zqdai** [comment]
@lynncui00 @cjcchen 我想了一下，脉冲的问题也许是我们的观测方法造成的：phxbinlogsvr（图中的bls57）是执行phxsql的管理工具拿到的，phxsqlproxy（图中sql57）的expire time则是通过共享内存取得的。

“脉冲”不止在尾端观测到。目前观察到跟运行/观测环境关系密切：在设置相同的情况下，在一台物理机上使用两台虚拟机安装phxql时几乎观测不到脉冲，在3台物理机集群上则可以普遍观测到。。

谢谢！

**Comment by zqdai** [comment]
看了一眼代码，该脉冲应该是期望的行为，原理：
1、binlogsvr使用了backup request模式响应查询。
2、每台机器的时钟存在一定的（虽然极小）误差。该实验中应是小于等于1秒钟。
在网络足够快时，有一台时间快的机器有时候比本机更早的响应了查询，然后进程就看到了不一致的时间。

这个脉冲在lease远大于机器时差时应该是不会影响系统的稳定的？也许在master选举后各台机器应该自动对时？

**Comment by cjcchen** [comment]
这个脉冲式期望行为的，不会影响系统的稳定。master在选择后，会用自己本机的时间加上lease作为本机的超时。因此解决了各机器时钟不一致时带来的在master的实际租约没超时时，其他slave的master租约已经超时的情况。

在 2016年10月16日 上午11:15，Zhengqing Dai <notifications@github.com>写道：

**Comment by wodesuck** [comment]
@zqdai proxy更新master不及时的问题已修复，欢迎拉取最新代码做测试 :smile:

**Comment by zqdai** [comment]
好的，谢谢！
