### ISSUE TITLE
请问下PhxSQL怎么实现读负载均衡呢？

### ISSUE THREAD

**Issue by jos666** [tencent-wechat/phxsql#51]
PhxSQL 读负载需要第三方软件支持还是自己有实现这个功能？
比如第三方负载软件 lvs  nginx haproxy mycat 负载呢？

**Comment by cjcchen** [comment]
读请求的负载均衡需要自己实现的。也可以通过第三方模块来支持。
另外注意的是，读请求分配到Slave机器，是有可能读到过期数据的。这些需要注意一下。
