### ISSUE TITLE
phxSQL连接方式和选主机制有没有具体说明？

### ISSUE THREAD

**Issue by Xing1214** [tencent-wechat/phxsql#53]
我在wiki中只找到安装文档但是对于phxSQL的使用没有说明？刚了解phxSQL，因为没有安装只是想先了解一下，有人可以分享一下使用情况吗？

**Comment by cjcchen** [comment]
在代码文件的tab下有详细的使用说明。默认是英文版，可以点击中文链接切换。

谢谢。

**Comment by Xing1214** [comment]
选主机制文档中只提到paxos协议进行master切换，但是协议中具体的算法以及演变过程并没有介绍很清楚，这方面还有较详细的文档可以参考吗？

**Comment by liusifan** [comment]
@Xing1214 请参考 phxpaxos 的 wiki https://github.com/tencent-wechat/phxpaxos/wiki
