### ISSUE TITLE
可以用跨机房的3台服务器来部署phxsql吗？

### ISSUE THREAD

**Issue by yurongliao** [tencent-wechat/phxsql#54]
3个机房的服务器内网IP互相不通。只有外网IP可以连接。
部署执行python install.py 的时候 -i参数指定了外网IP，etc/phxbinlogsvr.conf 里面的IP也确实是外网IP，
但是发现binlogsrv依然是listen内网IP，导致其他机房的服务器无法连接。请问这个有办法解决吗？

**Comment by cjcchen** [comment]
@yurongliao 该问题已经解决，可尝试更新一下代码，重新编译和部署。

谢谢你的反馈。

**Comment by yurongliao** [comment]
测试了一下，现在listen的都是外网IP了，不过phxsqlproxy54321端口无法连接，54322可以连接。
看了一下代码，发现phxsqlproxy/io_routine.cpp的CanExecute()里面也会判断IP地址，里面用的GetInnerIP，这个函数里也需要修改一下。

**Comment by wodesuck** [comment]
@yurongliao fixed，你可以再试一下

谢谢你的反馈。

**Comment by yurongliao** [comment]
测试通过了，非常感谢！

**Comment by GodStormBack** [comment]
可以说一下具体怎么解决的么，同样遇到这个问题

**Comment by GodStormBack** [comment]
@yurongliao 我也遇到同样的问题，可以告知您的解决方案么，同样是监听地址是内网地址，但是设置的是外网地址。

**Comment by lynncui00** [comment]
@GodStormBack 这个bug已经被修复，pull一下最新代码重新编译就可以解决了。
