### ISSUE TITLE
MYCAT能连phxSQL吗？

### ISSUE THREAD

**Issue by Xing1214** [tencent-wechat/phxsql#55]
MYCAT能连phxSQL吗？连接方式和mysql是一样的吗？

**Comment by liusifan** [comment]
PhxSQL对外提供服务的接口完全兼容MySQL，所以把一组PhxSQL当作一个MySQL就可以了。唯一有点不同的是一组PhxSQL有多台机器，这些机器的读写端口都可以提供服务，并且多台机器上的读写端口提供的服务是等价的。MyCAT可以连接同一组机器的任意一台的读写端口。

**Comment by Xing1214** [comment]
谢谢，很有用。
