### ISSUE TITLE
几个配置文件/工具的bug

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#56]
1、binary_operator.py 第49行
               return self.comm_kill_binary( 'phxbinlogsvf' )
进程名称似乎是拼写错误，应为
               return self.comm_kill_binary( 'phxbinlogsvr' )

2、my.cnf：当安装时指定端口为X时，发现 [mysqld] 部分的端口号变为X，而 [client] 并未改变（仍为模板里的11111）

3、my.cnf：配置中的 socket 安装后也没有更新，与 [mysqld] 部分不一致。
socket          = /tmp/percona.sock
应更新为：
socket          = /数据目录/percona.workspace/tmp/percona.sock

此外编译后的 mysql 客户端的默认配置文件搜索路径中并未包含 phxsql 配置文件的路径，直接执行在某些平台（CentOS 6.4）会报错，错误消息_类似_于: can't read dir /etc/mysql/my.conf 。

**Comment by wodesuck** [comment]
1,2,3 fixed

不过用mysql client连phxsql的时候，一般都指定54321或者54322端口，my.cnf里面的client配置好像并没什么用。

谢谢你的反馈。
