### ISSUE TITLE
普通mysql客户端可以登录Phxsql么

### ISSUE THREAD

**Issue by GodStormBack** [tencent-wechat/phxsql#57]
以及配置好Phxsql集群，如果想要从外部访问，使用普通的MySQL客户端可以直接进行访问么，需要做什么配置

**Comment by wodesuck** [comment]
参见 #55 

普通mysql客户端可以登录Phxsql，连接读写端口的请求会转发到主机进行读写操作，连接只读端口的请求会在所连机器上读取数据。

**Comment by GodStormBack** [comment]
非常感谢
