### ISSUE TITLE
可以用位于不同内网内的节点进行phxsql的搭建么

### ISSUE THREAD

**Issue by GodStormBack** [tencent-wechat/phxsql#58]
3个节点的内网IP互相不通。只有外网IP可以连接。
部署执行python install.py 的时候 -i参数指定了外网IP，etc/phxbinlogsvr.conf 里面的IP也确实是外网IP，
但是发现binlogsrv依然是listen内网IP，然后初始化的时候，不能完成初始化，提示get master fail。有什么解决方案么

**Comment by cjcchen** [comment]
@GodStormBack 如果可以的话麻烦更新一下代码，这个问题已经修复的了。

谢谢

**Comment by GodStormBack** [comment]
好的 非常感谢
