### ISSUE TITLE
deepin 15.3 x64系统 make编译phxsql到70%报错

### ISSUE THREAD

**Issue by xfree86** [tencent-wechat/phxsql#60]
[ 70%] Building CXX object storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/bndata.cc.o
In file included from /home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/util/dmt.h:679:0,
                 from /home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/ft/bndata.h:40,
                 from /home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/ft/bndata.cc:39:
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/ft/bndata.cc: In function ‘toku::dmt<klpair_struct, klpair_struct*, toku::klpair_dmtwriter>::copyout(unsigned int_, klpair_struct__, unsigned int, klpair_struct_)’:
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/util/dmt.cc:903:5: error: nonnull argument ‘outlen’ compared to NULL [-Werror=nonnull-compare]
     if (outlen) {
     ^~
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/util/dmt.cc:906:5: error: nonnull argument ‘out’ compared to NULL [-Werror=nonnull-compare]
     if (out) {
     ^~
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/ft/bndata.cc: In function ‘toku::dmt<klpair_struct, klpair_struct*, toku::klpair_dmtwriter>::copyout(unsigned int_, klpair_struct__, toku::dmt_internal::dmt_node_templated<klpair_struct>_)’:
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/util/dmt.cc:883:5: error: nonnull argument ‘outlen’ compared to NULL [-Werror=nonnull-compare]
     if (outlen) {
     ^~
/home/xfree/PhxSQL/phxsql/percona/storage/tokudb/PerconaFT/util/dmt.cc:886:5: error: nonnull argument ‘out’ compared to NULL [-Werror=nonnull-compare]
     if (out) {
     ^~
cc1plus: all warnings being treated as errors
storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/build.make:72: recipe for target 'storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/bndata.cc.o' failed
make[3]: **\* [storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/bndata.cc.o] Error 1
make[3]: Leaving directory '/home/xfree/PhxSQL/phxsql/percona'
CMakeFiles/Makefile2:2717: recipe for target 'storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/all' failed
make[2]: **\* [storage/tokudb/PerconaFT/ft/CMakeFiles/ft_static.dir/all] Error 2
make[2]: Leaving directory '/home/xfree/PhxSQL/phxsql/percona'
Makefile:160: recipe for target 'all' failed
make[1]: **\* [all] Error 2
make[1]: Leaving directory '/home/xfree/PhxSQL/phxsql/percona'
Makefile:25: recipe for target 'mysql' failed
make: **\* [mysql] Error 2
root@xfree-zs-app1-pc:/home/xfree/PhxSQL/phxsql# 
root@xfree-zs-app1-pc:/home/xfree/PhxSQL/phxsql# 
root@xfree-zs-app1-pc:/home/xfree/PhxSQL/phxsql# uname -a
root@xfree-zs-app1-pc:/home/xfree/PhxSQL/phxsql# Linux xfree-zs-app1-pc 4.4.0-3-deepin-amd64 #1 SMP Deepin 4.4.26-1 (2016-10-21) x86_64 GNU/Linux

**Comment by wodesuck** [comment]
试一下`CXXFLAGS=-Wno-nonnull-compare make`，看起来是gcc版本问题，导致percona编不过
