### ISSUE TITLE
用tools/restart.py重启phxbinlogsvr之后，log目录下的phxbinlogsvr.WARNING等link没有更新

### ISSUE THREAD

**Issue by yurongliao** [tencent-wechat/phxsql#61]
用tools/restart.py重启phxbinlogsvr之后，因为pid变化了，log的文件名也发生了变化，但phxbinlogsvr.WARNING、phxbinlogsvr.INFO、phxbinlogsvr.ERROR链接没有更新，还是指向之前的log文件。

**Comment by cjcchen** [comment]
@yurongliao 这个是glog自身的属性。详细情况看查看glog的官方文档。
