### ISSUE TITLE
phxsql连接问题

### ISSUE THREAD

**Issue by GodStormBack** [tencent-wechat/phxsql#63]
Phxsql搭建完成之后，在集群内部可以使用mysql命令进入数据库进行操作。但是在本地使用Navicat选择mysql连接方式进行连接，不能连接数据库。提示
1045- Access denied for user 'user'@'ip'

**Comment by wodesuck** [comment]
这是正常情况，默认限制了集群内部才能登录。你可以同普通mysql一样添加用户供外部访问。

**Comment by GodStormBack** [comment]
谢谢，已经解决了
