### ISSUE TITLE
mysql -uroot -h"集群某IP" -P$phxsqlproxy_port 一直无法进去mysql

### ISSUE THREAD

**Issue by thxCode** [tencent-wechat/phxsql#65]
在CentOS6.5下编译成功，同时已经初始化成功集群：
![image](https://cloud.githubusercontent.com/assets/3394724/19848754/7e9313be-9f8a-11e6-8884-67761e997155.png)

但是就是一直卡着进不去：
![image](https://cloud.githubusercontent.com/assets/3394724/19848776/a4e49362-9f8a-11e6-80c5-db5c4b56ed4c.png)

**Comment by wodesuck** [comment]
请检查一下libco是不是最新的版本，某个中间版本的libco可能导致这个现象。

拉取最新的libco并重新编译后，到phxsqlproxy目录执行`make clean && make`，然后把新编译出来的phxsqlproxy_phxrpc拷贝到install_package/sbin，`python2.7 restart.py -pphxsqlproxy`重启phxsqlproxy，看问题是否有修复。

**Comment by thxCode** [comment]
@wodesuck ，我直接git clone --recursive master，我观察到这个recursive出来的libco的版本是：`9f2bd17e81745a3b87fe3536b1d1ae1f83059437`，我按照您说的换成最新的，解决了这个问题。谢谢。
