### ISSUE TITLE
关于批量导入数据的问题

### ISSUE THREAD

**Issue by yurongliao** [tencent-wechat/phxsql#66]
请教一下。如果想把现有的MySQL数据迁移到PhxSQL，比如大概300G的数据，想要批量导入到PhxSQL，有什么好的工具或者方法吗？

**Comment by wodesuck** [comment]
[从现有MySQL数据库迁移](https://github.com/tencent-wechat/phxsql/wiki/%E4%BB%8E%E7%8E%B0%E6%9C%89MySQL%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)

写了一篇关于迁移的wiki，希望对你有帮助。

**Comment by yurongliao** [comment]
Thanks.
