### ISSUE TITLE
关于部署运行问题

### ISSUE THREAD

**Issue by henauy** [tencent-wechat/phxsql#67]
你好！

我按照编译手册编译了运行包(make package)，然后在一台主机部署了两个ubuntu 64位的容器
分别运行：
python2.7 install.py -i"192.168.02" -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f/tmp/data/
python2.7 install.py -i"192.168.03" -p 54321 -g 6000 -y 11111 -P 17000 -a 8001 -f/tmp/data/
运行成功。

然后让他们组成集群：
./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h"192.168.0.2,192.168.0.3" -p 17000
查看：
./phxbinlogsvr_tools_phxrpc -f GetMemberList -h192.168.0.2 -p 17000
返回信息：
get master 192.168.0.2 exprie time 1478002219
ip 192.168.0.2 port 17000
ip 192.168.0.2 port 17000

后面测试：
测试主机写：
mysql -uroot -h "192.168.0.2" -P 54321  < test1.sql
导入成功，并且两个数据库都能查到teset1.sql修改内容

测试的主机配置：
4核1.8GHz，内存 2G，Ubuntu 4.2.0-16-generic x86_64 GNU/Linux
Docker镜像也是64位的Ubuntu镜像

安装上述步骤，还是有下面问题：
1、使用 top 查看进程，发现有两个 phxsqlproxy_phx 进程，每个进程CPU使用率60+%，还有一个 phxbinlogsvr_ph 进程，CPU使用率10+%，而mysqld占用CPU很少，只占用了10%左右内存，因为未找到相关运行说明，不知道这运行状态是否正常。

2、使用 netstat -anop 查看连接数，发现在17000端口和11111端口出现大量 TIME_WAIT 状态的连接，大约有2000+个， 有是127.0.0.1:11111/17000（少量），也有是192.168.0.2:17000/11111的（大量），还有就是几十个 unix 3 [ ] STREAM CONNECTED 1858* {285|284}/phxsqlproxy_phx 连接。

3、查看phxsqlproxy日志 ERROR 日志很少几行没有ERROR标志，
WARNING日志有2w行：
UpdateGroupStatus: ret -94
UpdateGroupStatus: 47 ret 0 but no member inside 或者 UpdateGroupStatus: 92 GetMaster Succ
INFO日志大概有有3w行的
I1101 22:03:46.324321 344 phx_glog.cpp:74] run: 0 IORoutine is working ....
这些日志是否正常，是否通过配置调试等级减少日志信息。

**Comment by cjcchen** [comment]
1. 正常来说CPU应该不会那么高，可以尝试strace进程查看正在做什么事情
2. 11111端口是mysql的端口，而192.168.0.2:11111则应该是proxy访问mysql。可以进入mysql通过show processlist查看是否有连接一直连着和这些连接是否在进行某个查询。
3.日志可以通过设置配置文件（etc/phxsqlproxy.conf,etc/phxbinlogsvr.conf)的loglevel选项来调整其打印策略。选项的值为0-3，值越高打印的信息越多。

**Comment by tyronecai** [comment]
在CentOS6上用devtools-3中的GCC-4.9.2编译最新的0.8.5版本，并用三个Docker运行，一安装完毕还未导入数据就发现CPU情况同 @henauy ，在导入数据后出现大量TIME_WAIT连接。
**用perf top -p $pid 看到的是**
 40.66%  [kernel]            [k] finish_task_switch
  10.81%  [kernel]            [k] __bpf_prog_run
  10.80%  [kernel]            [k] _raw_spin_unlock_irqrestore
   5.21%  [kernel]            [k] pvclock_clocksource_read
   2.68%  libc-2.12.so        [.] klogctl
   2.47%  [kernel]            [k] kvm_clock_read
   2.25%  phxsqlproxy_phxrpc  [.] 0x0000000000036b93
   1.76%  [kernel]            [k] do_syscall_64
   1.50%  phxsqlproxy_phxrpc  [.] 0x00000000000368a9

**strace -ff -vv -tt -p $pid 看到的都是epoll_wait以及gettimeofday相关的**
[pid  1222] 09:57:38.988238 epoll_wait(51,  <unfinished ...>
[pid  1161] 09:57:38.988267 <... gettimeofday resumed> {1493258258, 987848}, NULL) = 0
[pid  1159] 09:57:38.988290 <... gettimeofday resumed> {1493258258, 987830}, NULL) = 0
[pid  1157] 09:57:38.988339 epoll_wait(42,  <unfinished ...>
[pid  1152] 09:57:38.988452 <... gettimeofday resumed> {1493258258, 987879}, NULL) = 0
[pid  1150] 09:57:38.988480 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid  1147] 09:57:38.988504 epoll_wait(40,  <unfinished ...>
[pid  1145] 09:57:38.988530 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid  1142] 09:57:38.988551 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid  1134] 09:57:38.988576 gettimeofday( <unfinished ...>
[pid  1346] 09:57:38.988651 gettimeofday( <unfinished ...>
[pid  1339] 09:57:38.988676 <... gettimeofday resumed> {1493258258, 988451}, NULL) = 0
[pid  1335] 09:57:38.988700 epoll_wait(94,  <unfinished ...>
[pid  1322] 09:57:38.988721 <... gettimeofday resumed> {1493258258, 988417}, NULL) = 0
[pid  1315] 09:57:38.988744 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid  1312] 09:57:38.988767 <... epoll_wait resumed> {}, 10240, 1) = 0
