### ISSUE TITLE
如何清理日志phxsql代理的日志文件？

### ISSUE THREAD

**Issue by liwei225** [tencent-wechat/phxsql#69]
测试过程中event文件把磁盘占满，如何安全有效进行清除？
7.9G	./phxbinlogsvr/paxoslog/g0/vfile
7.8G	./phxbinlogsvr/event_data

**Comment by wodesuck** [comment]
你可以通过phxbinlogsvr.conf中[AgentOption]下的CheckPointTime选项控制清理的频率。

具体可参考 [配置文件说明](https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#2-phxbinlogsvrconf)
