### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tencent-wechat/phxsql#7]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [EventIndex::CloseDB](https://github.com/tencent-wechat/phxsql/blob/892521e77b49bee0a08ab4444115ff66be55d9ae/phxbinlogsvr/core/storage/event_index.cpp#L57)
- [PhxBinlogStatFactory::SetPhxBinlogStat](https://github.com/tencent-wechat/phxsql/blob/892521e77b49bee0a08ab4444115ff66be55d9ae/phxbinlogsvr/statistics/phxbinlog_stat.cpp#L23)
- [PhxThread](https://github.com/tencent-wechat/phxsql/blob/892521e77b49bee0a08ab4444115ff66be55d9ae/phxsqlproxy/phxthread.cpp#L21)

**Comment by lynncui00** [comment]
thanks your suggestion:)
