### ISSUE TITLE
运行过程中时不时出现连接失败的问题

### ISSUE THREAD

**Issue by stevenwake** [tencent-wechat/phxsql#71]
phxsql部署了3个机房，广州两个点，无锡一个点（广州两个点之间的rtt是2ms，广州跟无锡之间的rtt是30ms），用脚本在业务机器上进行连接测试，每隔1s进行一次连接测试，跑了两个小时左右，出现了这么多次错误；
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading authorization packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading authorization packet', system error: 0
MySQL Error 2013:Lost connection to MySQL server at 'reading initial communication packet', system error: 0

**Comment by stevenwake** [comment]
检查错误日志，只发现了这些日志。
E1107 12:07:08.594369 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:07:10.642231 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:07:12.047232 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:10:20.875349 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:10:51.247498 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:10:53.090602 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:10:55.578526 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:10:57.663354 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:11:05.979408 23133 phx_glog.cpp:82] ERROR: httpcall -202
E1107 12:11:10.159397 23133 phx_glog.cpp:82] ERROR: httpcall -202

**Comment by wodesuck** [comment]
看上去是没拿到master的问题，麻烦请补充说明一下出错的是连接哪个机房，以及测试过程中是否有发生过换主。

**Comment by stevenwake** [comment]
广州 A，B机房，无锡C机房；A是主，过程中没有换主；
脚本对A，B，C机房都进行连接测试；
目前B，C机房连接有报错；
我怀疑下面这个超时的设置是不是比较短，目前调整成1000再测试看看会不会出现问题；
1、RoutineConnectWithTimeout(fd, (struct sockaddr*) &addr, sizeof(addr), 200);

**Comment by wodesuck** [comment]
A是主的话，连A一般不会转发到备，除非连接只读端口且关闭了MasterEnableReadPort。请问你的情况是这样吗？

**Comment by stevenwake** [comment]
确定是这个原因：RoutineConnectWithTimeout(fd, (struct sockaddr*) &addr, sizeof(addr), 200);
我调成1000后就很少出现问题了，调成3000后基本上没出现过问题了；
建议这个参数改成可配置，谢谢。

**Comment by wodesuck** [comment]
@stevenwake 好的，我会加一个配置项。但还是想问一下，是client连接主的时候发生错误吗，主是否将只读端口请求转发到备。
谢谢你的反馈。

**Comment by stevenwake** [comment]
我这边测试连的是读写端口，client直接连主的proxy的时候不会发生错误；
A（广州），B（广州），C（无锡）三个点部署phxsql，A作为master节点，B，C作为follow；
从D（广州），E（无锡），F（北京）三台业务机器上分别对A，B，C三个节点的读写proxy进行连接测试；
测试过程中：D，E，F 对A（主）的连接测试没有发生过错误；
                      D，E，F 对 B，C（从）的连接测试经常出现错误，因为连接的是读写端口，B和C的phsqlxproxy要跟A的phxsqlproxy 进行连接；（如果B，C跟的A网络出现抖动或者丢包，就很容易超时）

**Comment by wodesuck** [comment]
@stevenwake 明白了，那确实是这里的问题，我改一下。

**Comment by wodesuck** [comment]
bd5847f
