### ISSUE TITLE
Bug：phx_glog.cpp函数调用错乱

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#75]
文件phx_glog.cpp，以下代码似乎是错误的：Err被log到了Warning里，Info被log到Err里，Warning（debug）被log到了Info里。

void PhxGLog::LogDebug(const char *log_str) {
    LOG_STR(INFO, log_str);
}

void PhxGLog::LogErr(const char *log_str) {
    LOG_STR(WARNING, log_str);
}

void PhxGLog::LogImpt(const char *log_str) {
    LOG_STR(ERROR, log_str);
}

void PhxGLog::LogInfo(const char *log_str) {
    return LogImpt(log_str);
}

**Comment by wodesuck** [comment]
这里好像是有点乱。。多谢你的反馈

**Comment by wodesuck** [comment]
3942a25 fixed
