### ISSUE TITLE
colib bug：PID被假定为不能超过102400

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#76]
co_routine.cpp: 

static stCoRoutineEnv_t* g_arrCoEnvPerThread[ 102400 ] = { 0 };

采用数组的好处显而易见，但以pid索引这个数组很可能越界。需要该为其他数据结构。

发生越界时phxsql会无法启动。

**Comment by wodesuck** [comment]
这里确实是有这样的隐患，不过一般系统的pid_max很少设置这么大。我想libco这么做可能是出于运行效率考虑。

**Comment by zqdai** [comment]
那也不能以牺牲正确性来换性能啊。。。pid_max是可以手动设置的，而且没有规定说pid一定要从小往大分配，所以我觉得不能做这个假设，或者也要检查一下是否越界并且告知用户。。

**Comment by lynncui00** [comment]
看了一下colib的实现获取线程号用的是syscall，这个返回的线程号是进程内唯一的，并且是内核分配的，不会是一个很大的值。并且无论从小到大还是从大到小，对于数组来说也没啥影响？这个是Linux的系统调用，应该也不存在移植性的问题。

**Comment by wodesuck** [comment]
@zqdai 这个问题可以去libco提一个issue，跟他们做一下探讨

**Comment by zqdai** [comment]
关于"定制的系统"，我的意思是这个假定已经限制了 /proc/sys/kernel/pid_max 不能超过102400。而实际上在大型的服务器上可以是一个很大的值。事实上在我们的测试服务器上，这个值就非常大。

@wodesuck 哈哈，以为你们是一组的。

这个问题比较具体，我自己也可以修复。反馈到官方的原因是希望能少一些bug。

**Comment by lynncui00** [comment]
@zqdai 从这个角度来说却是不是很友好。参照 @wodesuck 做法:)

**Comment by zqdai** [comment]
嗯嗯，多谢，关掉了哈。
