### ISSUE TITLE
get in to retry logic 问题

### ISSUE THREAD

**Issue by stevenwake** [tencent-wechat/phxsql#80]
I1111 11:28:59.695493 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos7LearnerE::OnProposerSendSuccess END Learn value OK, value 1508 
E1111 11:28:59.695545 23216 phx_glog.cpp:82]  SMExecute gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622212 local checksum 9742702348900863465 new checksum 9742702348900863465, check done 
E1111 11:28:59.695878 23216 phx_glog.cpp:82]  AddEvent write data gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622212 instance id 11207867 checksum 9742702348900863465 ret 0 file EVENTDATA-11197908 run 0 ms 
E1111 11:28:59.696133 23216 phx_glog.cpp:82]  save event send gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622210 buffer gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622212 value size 1393 check sum 9742702348900863465, new checksum 
9742702348900863465 run 0 ms 
E1111 11:28:59.696137 24864 phx_glog.cpp:82]  GetEvents no data 
I1111 11:28:59.696436 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos8InstanceE::ReceiveMsgForLearner [Learned] New paxos starting, Now.Proposer.InstanceID 11207867 Now.Acceptor.InstanceID 11207867 Now.Learner.InstanceID 11207867 
I1111 11:28:59.696687 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos8InstanceE::ReceiveMsgForLearner [Learned] Checksum change, last checksum 2545379198 new checksum 337852711 
I1111 11:28:59.696704 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos8InstanceE::ReceiveMsgForLearner [Learned] New paxos instance has started, Now.Proposer.InstanceID 11207868 Now.Acceptor.InstanceID 11207868 Now.Learner.InstanceID 
11207868 
E1111 11:28:59.696707 24864 phx_glog.cpp:82]  GetEvent get gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622212 ret 0 
E1111 11:28:59.696956 24864 phx_glog.cpp:82]  GetEvent get gtid  ret 1 
E1111 11:28:59.697563 24864 phx_glog.cpp:82]  CountCheckSum get data check sum 9742702348900863465, max gtid 4bfff2ca-a0cf-11e6-ab78-246e9626b573:8622212, gtid check sum 9742702348900863465 data size 1393 
E1111 11:28:59.697945 24864 phx_glog.cpp:82]  GetEvent get gtid  ret 1 
E1111 11:28:59.698213 24864 phx_glog.cpp:82]  no data wait 
E1111 11:28:59.720422 23217 phx_glog.cpp:82]  Showy(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 1930804 checkpoint instanceid 11197909 now instanceid 11207868 
E1111 11:28:59.729266 23216 phx_glog.cpp:82]  Showy(0): PN8phxpaxos8InstanceE::OnReceivePaxosMsg Now.InstanceID 11207868 Msg.InstanceID 11207868 MsgType 7 Msg.from_nodeid 10113146384203915073 My.nodeid 14174116066552192833 Seen.L
atestInstanceID 11207834 
I1111 11:28:59.729609 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos8InstanceE::ChecksumLogic my last checksum 337852711 other last checksum 337852711 
I1111 11:28:59.729630 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos7LearnerE::OnProposerSendSuccess START Msg.InstanceID 11207868 Now.InstanceID 11207868 Msg.ProposalID 18 State.AcceptedID 0 State.AcceptedNodeID 0, Msg.from_nodeid 
10113146384203915073 
E1111 11:28:59.730295 23216 phx_glog.cpp:82]  Showy(0): PN8phxpaxos8InstanceE::OnReceivePaxosMsg Now.InstanceID 11207868 Msg.InstanceID 11207869 MsgType 3 Msg.from_nodeid 10113146384203915073 My.nodeid 14174116066552192833 Seen.L
atestInstanceID 11207834 
I1111 11:28:59.730609 23216 phx_glog.cpp:74]  Imp(0): PN8phxpaxos7LearnerE::OnProposerSendSuccess START Msg.InstanceID 11207868 Now.InstanceID 11207868 Msg.ProposalID 18 State.AcceptedID 0 State.AcceptedNodeID 0, Msg.from_nodeid 
10113146384203915073 
W1111 11:28:59.730633 23216 phx_glog.cpp:78]  ERR(0): PN8phxpaxos8InstanceE::ReceiveMsgForAcceptor InstanceID not same, get in to retry logic

**Comment by stevenwake** [comment]
这条提议，从节点msgType 3没收到，只接收到msgType 7，导致进入retry logic，想问下什么情况下会出现这种问题？

E1111 11:28:59.729266 23216 phx_glog.cpp:82] Showy(0): PN8phxpaxos8InstanceE::OnReceivePaxosMsg Now.InstanceID 11207868 Msg.InstanceID 11207868 MsgType 7 Msg.from_nodeid 10113146384203915073 My.nodeid 14174116066552192833 Seen.L

**Comment by lynncui00** [comment]
这个有可能是UDP消息乱序了，先收到了msgType 7的消息。

**Comment by stevenwake** [comment]
能不能增加tcp传输的选择，机房间没专线，udp丢消息发生的概率还是比较高

**Comment by stevenwake** [comment]
还有一点想问下，为什么使用udp传输

**Comment by lynncui00** [comment]
udp的性能更好。目前默认是小于4k使用udp，大于4k使用tcp。我们可以加一个配置项给你配置这个值。

**Comment by stevenwake** [comment]
帮忙增加一下配置选项，谢谢。

**Comment by wodesuck** [comment]
48023ac6eb87f3709ac32e81977e6dcfbfa3ff15 加了一个配置项，phxbinlogsvr.conf里[PaxosOption]下的UDPMaxSize，超过这个大小就会走TCP。
