### ISSUE TITLE
新的paxos库好像有bug

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#81]
使用最新的代码，集群无法正常初始化。。

**Comment by lynncui00** [comment]
发一下版本号我看看是不是问题版本，有一个中间版本确实有问题。

**Comment by zqdai** [comment]
版本：
 f851064bb23192b2f6f866de091799580fa5b086 third_party/phxpaxos (v1.0.2-11-gf851064)
非常感谢

**Comment by lynncui00** [comment]
f851064bb23192b2f6f866de091799580fa5b086  这个应该是v1.1.1最新版本，应该是没问题的版本。你括号里面的v1.0.2是怎么来的？

**Comment by zqdai** [comment]
输出是从 git submodule 得到的。刚才的问题是集群不能正确初始化，但现在重新编译后又不能重现了。感觉是编译的方式引起的。

编译的时候没有clean mysql，结果就出现了一些奇怪的问题。我再从头编译一遍试试。谢谢。

**Comment by zqdai** [comment]
暂未重现。close。
