### ISSUE TITLE
phxbinlogsvr_tools_phxrpc 工具修改默认管理员账号密码 报错

### ISSUE THREAD

**Issue by tihu2016** [tencent-wechat/phxsql#82]
[root@linux_server_1 sbin]# cd ..
[root@linux_server_1 phxsql]# /root/phxsql/sbin/phxbinlogsvr_tools_phxrpc --help

Usage: /root/phxsql/sbin/phxbinlogsvr_tools_phxrpc [-c <config>] [-f <func>] [-v]
    -f PHXEcho -s <string>
    -f GetMasterInfoFromGlobal -h <host> -p <port>
    -f GetLastSendGtidFromGlobal -h <host> -p <port> -u<gtid>
    -f SetExportIP -h <host> -p <port>
    -f AddMember -h <host> -p <port> -m <member ip>
    -f RemoveMember -h <host> -p <port> -m <member ip>
    -f SetMySqlAdminInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new admin username> -D <new admin pwd>
    -f SetMySqlReplicaInfo -h <host> -p <port> -u <admin username> -d <admin pwd> -U <new replica username> -D <new replica pwd>
    -f GetMemberList -h <host> -p <port>
    -f InitBinlogSvrMaster -h <ip1,ip2,ip3(ip1 is master, others are slaves)> -p <port>

[root@linux_server_1 phxsql]#
[root@linux_server_1 phxsql]#  /root/phxsql/sbin/phxbinlogsvr_tools_phxrpc  -f SetMySqlAdminInfo -h 192.168.20.60 -p 17000 -u root -d -U root -D 123@xlm
get master 192.168.20.63 expire time 1478855015
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
[root@linux_server_1 phxsql]# ^C
[root@linux_server_1 phxsql]#

因为管理员账号默认账号密码为（"root"，""） 所以我 -d 参数没有填写 ；

想请教一下 改怎么解决这个问题

**Comment by wodesuck** [comment]
`-d ""`

**Comment by tihu2016** [comment]
非常感谢，修改成功了
