### ISSUE TITLE
使用 test_phxsql.sh 怎么报错了

### ISSUE THREAD

**Issue by tihu2016** [tencent-wechat/phxsql#83]
./test_phxsql.sh 17000 192.168.20.60
create database to phxsql
mysql -uroot -h192.168.20.60 -P17000 -e "create database if not exists test_phxsql;"
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
create database to phxsql fail

使用 test_phxsql.sh 怎么报错了 还请帮忙解决一下

**Comment by wodesuck** [comment]
我猜你可能是想执行`./test_phxsql.sh 54321 192.168.20.60`
