### ISSUE TITLE
选主时间和选主条件？

### ISSUE THREAD

**Issue by Xing1214** [tencent-wechat/phxsql#84]
选主时间是和master租约一样可配置的吗？选主时间内phxSQL是处于无master状态的吗？
选主条件或者说phxSQL状态机都包括哪些？是可配置的吗？

**Comment by lynncui00** [comment]
选主会尽最快速度进行，不需配置。选主过程中是处于无Master状态。
选主条件是当Master信息过期且Mysql的innodb数据已经和binlogsvr对齐。这两个条件是必须的，目前选主条件无法配置。
