### ISSUE TITLE
phxSQL数据同步过程中，如何确定数据从logsvr同步到了mysql实例？

### ISSUE THREAD

**Issue by Xing1214** [tencent-wechat/phxsql#85]
phxSQL数据同步过程中，如何确定数据从logsvr同步到了mysql实例？是在数据同步到logsvr，提交之后，在发起一次确认流程，确认binlog日志确定被同步到了mysql实例，还是说，不关心logsvr同步到mysql实例这一步。如果不关心，那logsvr的binlog日志在同步到mysql实例过程中出错导致数据未被同步到实例，这样数据还是不一致的，或者他们之间同步的时间过长。

**Comment by weipatty** [comment]
确实，之前有遇到 relaylog出错了，备节点其实一直是没追上的， 不过这个应该算是mysql的问题吧。
paxos只能确保binlog是一致的，

**Comment by lynncui00** [comment]
当relaylog出现问题导致Slave没有追上，这时候这个节点是无法被提升为Master的。而故障容灾中Master的切换总能保证数据一致，读Master的数据总能保证是最新的。至于Slave一直出错的问题，需要有效的监控及时发现进行处理或者直接替换机器。
