### ISSUE TITLE
Phxbinlogsvr Bug：集群无法正常初始化，出现问题后也无法从过期状态恢复

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#86]
可能有1～2个较为严重的逻辑漏洞（可能是同一个问题）：
1、第一个集群不能正常初始化，不能稳定重现。
2、重现后会发现整个集群会处于错误的状态，目前我重现之后，集群出现了master过期，然而却不能选举新master的情况。debug后发现系统出在以下状态：

master节点（初始化时指定）
--
 在AgentMonitor中， 可以看到status = RUNNING，此时master此时已经处在过期状态，照理来说应该触发CheckMasterTimeOut()，但实际上，由于master处在过期状态时，check_master始终为false，原因是CheckRuning()中的这段逻辑：
 bool is_master = master_manager_->CheckMasterBySvrID(option_->GetBinLogSvrConfig()->GetEngineSvrID());
CheckMasterBySvrID()有一个默认的第二参数，导致该检查返回false。

这样一来，master永远不知道自己是master，也无法执行 CheckMasterTimeOut()。

slave节点
--
Slave节点处于status=MASTER_CHANGING状态。而且由于自己不是master，check_master同样为false。也不能执行CheckMasterTimeOut()。

因此，初始化时若系统处于过期状态时，系统将不能从这个状态中恢复。

p.s. paxos库中已经有了选主的逻辑（MasterDamon中），不明白为什么phxbinlogsvr还要自己实现一个？

**Comment by lynncui00** [comment]
关于为何不用paxos库中的选主逻辑，这里先回答一下。
paxos库的选主条件是状态机的数据一定是最新的，但在phxsql上，状态机的数据实际是binlog，而除了这一层数据，还有mysql的innodb数据，由于两层数据的分离，导致phxsql的选主条件多了一个innodb数据的最新保证，所以两个的选主条件是不一样的。

**Comment by lynncui00** [comment]
关于为何不用paxos库中的选主逻辑，这里先回答一下。
paxos库的选主条件是状态机的数据一定是最新的，但在phxsql上，状态机的数据实际是binlog，而除了这一层数据，还有mysql的innodb数据，由于两层数据的分离，导致phxsql的选主条件多了一个innodb数据的最新保证，所以两个的选主条件是不一样的。

**Comment by cjcchen** [comment]
master节点
>在AgentMonitor中， 可以看到status = RUNNING，此时master此时已经处在过期状态，照理来说应该触发CheckMasterTimeOut()，但实际上，由于master处在过期状态时，check_master始终为false，原因是CheckRuning()中的这段逻辑：
>bool is_master = master_manager_->CheckMasterBySvrID(option_->GetBinLogSvrConfig()->GetEngineSvrID());
>CheckMasterBySvrID()有一个默认的第二参数，导致该检查返回false。
>
>这样一来，master永远不知道自己是master，也无法执行 CheckMasterTimeOut()。

在master和slave中，CheckMasterBySvrID 这个接口与是否是master没关系，只要满足条件即可。
>if (check_master && now - last_check >= option_->GetBinLogSvrConfig()->GetMonitorCheckStatusPeriod()) {
            CheckMasterTimeOut();
            CheckCheckPointFiles();
            last_check = now;
        }

如果代码进入不了上面的逻辑，则说明master节点的状态有点问题，譬如mysql连接不上等等


slave节点
>Slave节点处于status=MASTER_CHANGING状态。而且由于自己不是master，check_master同样为false。也不能执行CheckMasterTimeOut()。

slave的MASTER_CHANGING表示他在处理master改变时的状态切换，状态还没切换结束，结束后会变成RUNNING状态。而在MASTER_CHANGING状态，slave所做的事情就是检查mysql的relaylog和检查mysql的slave线程是否在运行
>vector < string > gtid_list;
        int ret = SlaveMonitor::SlaveCheckRelayLog(option_, &gtid_list);
        if (ret == MYSQL_FAIL)
            return ret;
        ColorLogInfo("%s relay log has existed, relaylog size %zu", __func__, gtid_list.size());
>
 >       return CheckSlaveRunningStatus();

如果slave没有执行CheckMasterTimeOut那就说明mysql的状态出现问题。check_master的值是false。
>if (check_master && now - last_check >= option_->GetBinLogSvrConfig()->GetMonitorCheckStatusPeriod()) {
            CheckMasterTimeOut();
            CheckCheckPointFiles();
            last_check = now;
        }


因此，这里可以查看一下binlogsvr的日志，看是哪一步出问题导致状态检查失败，从而无法开始选举新的master。

**Comment by zqdai** [comment]
Debug 发现 Slave节点的问题是，MasterStorage中replication user的用户名和密码皆为空，实际上MasterInfo里的replication_user_size是0。另外Relay log的检查是通过的。

调用栈如下：

#0  phxbinlog::SlaveMonitor::SlaveStart (option=0xd8cf50 <phxbinlog::Option::GetDefault()::option>, master_ip=..., master_port=@0x7f2ba17fa85c: 6000, read_only=true) at slave_monitor.cpp:93
#1  0x00000000004580e0 in phxbinlog::SlaveMonitor::CheckSlaveRunningStatus (option=0xd8cf50 <phxbinlog::Option::GetDefault()::option>, export_ip=0x0, export_port=0x0) at slave_monitor.cpp:135
#2  0x0000000000453906 in phxbinlog::AgentMonitor::CheckSlaveRunningStatus (this=0x27e2b60) at agent_monitor.cpp:351
#3  0x0000000000453600 in phxbinlog::AgentMonitor::CheckMasterInit (this=0x27e2b60) at agent_monitor.cpp:302
#4  0x00000000004524c7 in phxbinlog::AgentMonitor::Process (this=0x27e2b60) at agent_monitor.cpp:103
#5  0x000000000048d1e9 in phxsql::ThreadBase::ThreadProcess (arg=0x27e2b60) at thread_base.cpp:33
#6  0x00007f2bab42f9d1 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f2baaef88fd in clone () from /lib64/libc.so.6

**Comment by zqdai** [comment]
补充信息：
1、master节点和slave节点的mysql出现了数据不一致的问题。slave上没有replica这个用户。master节点上的mysql里是有replica这个用户的

2、master节点和slave节点上的MasterInfo内容是一致的，奇怪的是，里边只有admin user信息，replica user的信息却都是空的

**Comment by cjcchen** [comment]
@zqdai 这种通常表现为初始化的时候向mysql添加replica信息失败。不确定是否是mysql安装的时候出现问题。
可尝试重新初始化集群。
如果仍然出现，请检查一下mysql的phxsync插件是否启动成功。
如果仍未能解决，请再次联系。

谢谢

**Comment by zqdai** [comment]
谢谢！我正在尝试重现。

**Comment by cjcchen** [comment]
@zqdai 这种情况通常是mysql加载phxsync插件失败导致的。

**Comment by zqdai** [comment]
这几天在我的虚拟机上可以稳定重现了（虽然重现的具体条件还不知道，同时在另一个物理集群上不能重现概率又很低），跟上次的问题可能略有差异。的确跟mysql关系很大。现象如下，log附在最后：
1、phxsql 初始化 mysql 反复失败。
2、然而，由于在初始化期间phxbinlogsvr并不发送心跳信息，导致binlogsvr租约过期，在过期后phxbinlogsvr认为自己是slave，然后就判断初始化成功了（实际上并没有，这里好像是binlogsvr的未能正确这种情况）。
3、过期后出现上述情况，或者目前可稳定重现的这一种情况：另一个机器没有收到任何paxos消息，始终处于NOTHING的状态。执行初始化的机器则出在过期且无法恢复的状态。
4、目前观测到mysql出现的情况都是卡死在某个初始化时要执行的语句上，例如：

mysql> show processlist\G

*************************** 1. row ***************************
           Id: 19
         User: root
         Host: 127.0.0.1:42125
           db: NULL
      Command: Query
         Time: 1615
        State: query end
         Info: flush privileges
    Rows_sent: 0
Rows_examined: 0
*************************** 2. row ***************************
           Id: 22
         User: root
         Host: 127.0.0.1:42263
           db: NULL
      Command: Query
         Time: 1610
        State: query end
         Info: flush privileges
    Rows_sent: 0
Rows_examined: 0
*************************** 3. row ***************************
           Id: 349
         User: root
         Host: 127.0.0.1:52480
           db: NULL
      Command: Query
         Time: 0
        State: init
         Info: show processlist
    Rows_sent: 0
Rows_examined: 0
3 rows in set (0.00 sec)

另一种情况：卡在grant语句，System lock状态。
mysql> show processlist;
18  root 	127.0.0.1:42548 	NULL 	Query 	485 	System lock 	grant all privileges on . to 'root'@'172.16.11.116' with grant option 	0 	0 

从以上情况看，似乎是mysql执行语句时耗时过长，导致了phxbinlogsvr租约过期，然后mysql再执行语句时卡死在插件中（似乎是插件要想phxbinlogsvr发送binlog，但显然它已经不合法而无法完成）。整个系统处在死锁状态。

phxbinlogsvr的日志（我做了一些改动，为了防止出现大量重复的错误消息并在一些情况下打印callstack，中文是我加的注释，方便阅读）：
E1202 10:41:41.410632  3618 phx_glog.cpp:80] Restarting PaxosAgent （系统收到了初始化命令）
E1202 10:41:45.040925  3861 phx_glog.cpp:80] MasterStorage::SetMaster: master changing, new svr id 2886732660, ip 172.16.11.116 (export ip :0), expire time 1480646515 update time 1480646505, version 0, instance id 1, user info size (0, 0), user info in MasterManager (,)
E1202 10:41:46.000144  3605 phx_glog.cpp:80] AgentMonitor::Process: recv master info during WAITING, svrid 2886732660, version 1, code fall through to MASTER_CHANGING
E1202 10:41:46.015537  3605 phx_glog.cpp:80] AgentMonitor: CheckMasterInit passed, status change to MASTER_CHANGING_INIT, code fall through
E1202 10:41:50.025629  3605 phx_glog.cpp:80] MasterMonitor::CheckMasterInit: mysql flush privileges failed, callstack:
0:      (_ZN6phxsql22LogErrMsgWithCallStackEPKcz+0xcf) [0x70b957]
1:      (_ZN9phxbinlog13MasterMonitor15CheckMasterInitEPKNS_6OptionE+0x19f) [0x6d19a1]
2:      (_ZN9phxbinlog12AgentMonitor10MasterInitEv+0x123) [0x6ceccd]
3:      (_ZN9phxbinlog12AgentMonitor7ProcessEv+0x344) [0x6ce430]
4:      (_ZN6phxsql10ThreadBase13ThreadProcessEPv+0x2b) [0x70ac45]
5:      /lib64/libpthread.so.0() [0x3e0a807aa1]
6:      (clone+0x6d) [0x3e0a4e8aad]
E1202 10:41:50.025699  3605 phx_glog.cpp:80] AgentMonitor: MasterInit failed, ret 5002, retrying （从这个时间间隔看，这里看起来似乎是因为执行时间或者连接时间超时退出的，我设置了4秒）
E1202 10:41:55.004225  3605 phx_glog.cpp:80] AgentMonitor: MasterInit failed, ret 5002, retrying
E1202 10:41:56.000182  3605 phx_glog.cpp:80] AgentMonitor: MasterInit passed, status change to RUNNING, code fall through （可以看到这里租约已经过期了，租约是10秒，而系统却认为初始化成功）
E1202 10:41:56.003437  3605 phx_glog.cpp:80] ^[[47;31m something err in slave?, reboot slave ^[[0m
E1202 10:41:56.011806  3605 phx_glog.cpp:80] AgentMonitor::IsSlaveReady:failed to get max gtid from EventManager, callstack:
0:      (_ZN6phxsql22LogErrMsgWithCallStackEPKcz+0xcf) [0x70b957]
1:      (_ZN9phxbinlog12AgentMonitor12IsSlaveReadyEv+0xe9) [0x6cfa31]
2:      (_ZN9phxbinlog12AgentMonitor12CheckRunningEv+0x342) [0x6ce9c4]
3:      (_ZN9phxbinlog12AgentMonitor7ProcessEv+0x3f7) [0x6ce4e3]
4:      (_ZN6phxsql10ThreadBase13ThreadProcessEPv+0x2b) [0x70ac45]
5:      /lib64/libpthread.so.0() [0x3e0a807aa1]
6:      (clone+0x6d) [0x3e0a4e8aad]
E1202 10:41:56.011890  3605 phx_glog.cpp:80] AgentMonitor: CheckRunning passed

**Comment by zqdai** [comment]
希望官方能够指点一下，谢谢！

**Comment by zqdai** [comment]
经过debug，mysql是没有问题的，当前所知的情况：
1、mysql在执行语句后要发送binlog，但binlogsvr没有回复，mysql卡死在recv系统调用上
2、binlogsvr发送paxos event，卡死在：phxpaxos::CommitCtx::GetResult，代码如下。该代码在等待另一个线程把m_bIsCommitEnd设为true。

int CommitCtx :: GetResult(uint64_t & llSuccInstanceID)
{
 while (!m_bIsCommitEnd)。{  
m_oSerialLock.WaitTime(1000); 
}
...
}

综上，问题出现在新paxos库中的可能性比较大。

**Comment by lynncui00** [comment]
这个可能是paxos的Propose操作一直无法成功，具体原因需要paxos库的日志分析一下。
可以grep paxos相关的日志贴上来看看。

**Comment by zqdai** [comment]
从日志看，paxos SetResult的线程Timeout了，然后反复重试，而反复Timeout。。。

W1205 20:48:06.076061  2707 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos9CommitCtxE::NewCommit OK, valuesize 191 ^[[0m
W1205 20:48:06.077057  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::NewValue skip prepare, directly start accept ^[[0m
W1205 20:48:06.077497  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Accept START ProposalID 1 ValueSize 191 ValueLen 191 ^[[0m
W1205 20:48:06.080425  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::AddAcceptTimer timeoutms 2000 ^[[0m
W1205 20:48:06.080476  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Accept END ^[[0m
W1205 20:48:06.080516  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8InstanceE::ChecksumLogic my last checksum 3769950297 other last checksum 3769950297 ^[[0m
W1205 20:48:06.080587  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnAccept START Msg.InstanceID 3 Msg.from_nodeid 8361795464063885121 Msg.ProposalID 1 Msg.ValueLen 191 ^[[0m
W1205 20:48:06.084784  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnAccept END Now.InstanceID 3 ReplyNodeID 8361795464063885121 ^[[0m
W1205 20:48:06.084834  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnAcceptReply START Msg.ProposalID 1 State.ProposalID 1 Msg.from_nodeid 8361795464063885121 RejectByPromiseID 0 ^[[0m
W1205 20:48:06.084859  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnAcceptReply END ^[[0m
W1205 20:48:06.308501  4061 phx_glog.cpp:76] STATUS(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instanceid (no checkpoint) now instanceid 3
W1205 20:48:06.939515  4061 phx_glog.cpp:76] STATUS(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instanceid (no checkpoint) now instanceid 3
W1205 20:48:07.081182  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnAcceptTimeout OK ^[[0m
W1205 20:48:07.081372  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Prepare START Now.InstanceID 3 MyNodeID 8361795464063885121 State.ProposalID 1 State.ValueLen 191 ^[[0m
W1205 20:48:07.081413  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::AddPrepareTimer timeoutms 2000 ^[[0m
W1205 20:48:07.081431  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Prepare END OK ^[[0m
W1205 20:48:07.081450  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnPrepare START Msg.InstanceID 3 Msg.from_nodeid 8361795464063885121 Msg.ProposalID 1 ^[[0m
W1205 20:48:07.081744  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnPrepare END Now.InstanceID 3 ReplyNodeID 8361795464063885121 ^[[0m
W1205 20:48:07.081794  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareReply START Msg.ProposalID 1 State.ProposalID 1 Msg.from_nodeid 8361795464063885121 RejectByPromiseID 0 ^[[0m
W1205 20:48:07.081814  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareReply END ^[[0m
W1205 20:48:07.318903  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn START ^[[0m
W1205 20:48:07.319021  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn END InstanceID 3 MyNodeID 8361795464063885121 ^[[0m
W1205 20:48:09.081377  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareTimeout OK ^[[0m
W1205 20:48:09.081516  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Prepare START Now.InstanceID 3 MyNodeID 8361795464063885121 State.ProposalID 1 State.ValueLen 191 ^[[0m
W1205 20:48:09.081552  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::AddPrepareTimer timeoutms 4000 ^[[0m
W1205 20:48:09.081570  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::Prepare END OK ^[[0m
W1205 20:48:09.081590  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnPrepare START Msg.InstanceID 3 Msg.from_nodeid 8361795464063885121 Msg.ProposalID 1 ^[[0m
W1205 20:48:09.090826  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8AcceptorE::OnPrepare END Now.InstanceID 3 ReplyNodeID 8361795464063885121 ^[[0m
W1205 20:48:09.090889  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareReply START Msg.ProposalID 1 State.ProposalID 1 Msg.from_nodeid 8361795464063885121 RejectByPromiseID 0 ^[[0m
W1205 20:48:09.090915  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareReply END ^[[0m
W1205 20:48:09.444341  4061 phx_glog.cpp:76] STATUS(0): PN8phxpaxos7CleanerE::run sleep a while, max deleted instanceid 0 checkpoint instanceid (no checkpoint) now instanceid 3
W1205 20:48:10.216182  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn START ^[[0m
W1205 20:48:10.216349  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn END InstanceID 3 MyNodeID 8361795464063885121 ^[[0m
W1205 20:48:12.839648  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn START ^[[0m
W1205 20:48:12.839818  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos7LearnerE::AskforLearn END InstanceID 3 MyNodeID 8361795464063885121 ^[[0m
W1205 20:48:13.081939  4060 phx_glog.cpp:76] ^[[44;37m Imp(0): PN8phxpaxos8ProposerE::OnPrepareTimeout OK ^[[0m

**Comment by lynncui00** [comment]
其他节点没有响应这个节点发出的任何网络包，这个得看看其他节点的情况了。

**Comment by zqdai** [comment]
谢谢，经过debug确认是防火墙的问题。

看了一点paxos的代码，写的很漂亮，质量很高，手动点赞！
