### ISSUE TITLE
提问：为什么slave要随机多sleep 0～10秒

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#87]
看到代码中有这样的逻辑，master信息更新后，slave会随时多睡0～10秒。不知道这种设计是否有理论依据？还是只是出于某种工程上的考虑（性能等）？

这里，我觉得至少写死10秒是不对的。

**Comment by lynncui00** [comment]
这是防止极端情况下Master时钟变快或者Slave时钟变慢从而导致Master信息在Slave比Master先过期，这个是一个保底策略，没有对错，slave不多sleep也是一般也是没问题的。

**Comment by zqdai** [comment]
谢谢～
