### ISSUE TITLE
Phxbinlogsvr issue: MasterMonitor 的 CheckMasterRunningStatus似乎有bug

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#88]
如题。

1、master在检查倒slave_running=ON时，调用了SlaveMonitor::SlaveStart。实际应该调用：MasterMonitor::MasterStart

```
int MasterMonitor::CheckMasterRunningStatus(const Option *option) {
    MySqlManager *mysql_manager = MySqlManager::GetGlobalMySqlManager(option);
    string slave_running;
    int ret = mysql_manager->GetValue("status", "Slave_running", &slave_running);
    if (ret) {
        return MYSQL_FAIL;
    }

    if (slave_running == "ON") {
        ColorLogWarning("something wrong, restart");
        if (SlaveMonitor::SlaveStart(option, "127.0.0.1", option->GetBinLogSvrConfig()->GetEnginePort()))
            return MYSQL_FAIL;
        return OK;
    }
    ColorLogInfo("master is running(maybe)");

    return OK;
}

```

--更正--
2、不好意思，Slave这个check是对的，我搞错了。。

**Comment by cjcchen** [comment]
monitor不能直接调用MasterStart的。
master的重新启动必须要先slave启动，然后检查slave状态，接着发送成为master的paxos请求，最后才能真正的成为master。
因此必须要经历从slave到master的过程。确保master的数据正确性。

**Comment by zqdai** [comment]
多谢指点！

**Comment by weipatty** [comment]
我也看到这， 有个疑问：

int MasterMonitor::CheckMasterRunningStatus(const Option *option) {
    MySqlManager *mysql_manager = MySqlManager::GetGlobalMySqlManager(option);
    string slave_running;
    int ret = mysql_manager->GetValue("status", "Slave_running", &slave_running);
    if (ret) {
        //slavecheckrunning return ok
        return MYSQL_FAIL;
    }

为啥 master的checkrunning 这里返回 fail 而slave 的返回ok呢？
