### ISSUE TITLE
从现有mysql迁移的那篇贴子是不是写错了。。

### ISSUE THREAD

**Issue by weipatty** [tencent-wechat/phxsql#90]
https://github.com/tencent-wechat/phxsql/wiki/%E4%BB%8E%E7%8E%B0%E6%9C%89MySQL%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB

这里 -s0表示保留现有数据库 应该是s1吧？   

看脚本是为1才不rm -fr 的。。

也没细看脚本，
顶啊，血的教训啊。

**Comment by wodesuck** [comment]
的确写反了... so sorry :fearful: 
现在改过来了，多谢你的反馈 :joy:
