### ISSUE TITLE
[bug] Master进程binlogsvr被kill后，租约过期之前，从slave连接读写端口执行SQL会导致无限等待

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#93]
重现步骤
1、3台机器（两台应该也可以），kill掉master的binlogsvr进程
2、迅速在slave节点连接读写端口并执行sql语句
3、陷入无限等待。

造成这个等待的原因是 mysql 一直会被卡在发送binlog的函数里。在这种情况下，binlogsvr既然已经挂掉了，是不是应该返回错误并回滚事务？

**Comment by wodesuck** [comment]
mysql 发送binlog时观察到 binlogsvr 挂掉，有两种可能：
1. 因为 binglogsvr 挂掉，binlog 发送失败。
2. 这条 binlog 成功被 paxos 协议通过，但是 binlogsvr 返回结果前挂掉。

mysql 只能观察到 binlogsvr 挂掉，但不能分辨是哪种情况，因此需要等待 binlogsvr 重启后告诉它最终结果，才决定是否回滚事务。

**Comment by zqdai** [comment]
等待的确也是一种合理的选择。这种情况下，无论等待或者让mysql自杀，对客户端来说已经都不是透明的，可否增加一个选项，比如一个超时的配置，为负值时就选择一直等，否则超时时自杀，强制断开客户端的连接？ ：）

**Comment by wodesuck** [comment]
超时配置理论上应该可以加，但我觉得还需要考虑：首先是上述情况下超时自杀后，mysql 启动需要获取 binlogsvr 的 gtid 信息，因此重启后 mysql 也是不可用的；其次是自杀不仅断开当前等待事务提交的连接，而且也会断开其他所有并发连接，包括正常的读请求。我认为，如果需要设置超时，由 client 来实现可能更合适。

**Comment by zqdai** [comment]
明白了，非常感谢你的耐心解释！
