### ISSUE TITLE
phxsql集群停止工作了，怎么让phxsql集群重新启动呢

### ISSUE THREAD

**Issue by tihu2016** [tencent-wechat/phxsql#94]
因环境变迁，运行phxsql集群的三台服务器都停止运行，并迁移到新的物理环境中；想请教一下phxsql集群怎么重新启动

**Comment by wodesuck** [comment]
进入`tools`目录，执行`python2.7 restart.py -pphxbinlogsvr`, `python2.7 restart.py -pphxsqlproxy`, `python2.7 restart.py -pmysql`

**Comment by tihu2016** [comment]
谢谢了！
