### ISSUE TITLE
信号处理器可能会导致(phxsqlproxy)主线程死锁，从而有些线程不能成功启动

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#95]
快速操作时会发生该问题，具体原理：如果在创建新线程malloc期间收到SIGHUP信号，由于信号处理器中又调用了malloc，从而导致死锁，call stack如下。

由于phxsqlproxy在我的脚本里最后一个启动（启动后shell立刻退出发出SIGHUP），所以目前该问题仅发现于phxsqlproxy。

#0 0x00007fb6b58c005e in __lll_lock_wait_private () from /lib64/libc.so.6
#1 0x00007fb6b584516b in _L_lock_9503 () from /lib64/libc.so.6
#2 0x00007fb6b58426a6 in malloc () from /lib64/libc.so.6
#3 0x0000000000753778 in operator new (sz=184) at ../../../../gcc-4.9.4/libstdc+-v3/libsupc+/new_op.cc:49
#4 0x000000000060cf6d in google::LogMessage::Init(char const*, int, int, void (google::LogMessage::*)()) ()
#5 0x000000000060cd99 in google::LogMessage::LogMessage(char const*, int, int) ()
#6 0x00000000005e51f2 in phxsql::PhxGLog::LogErr (log_str=0x7ffff8679a20 "receive signal 1") at phx_glog.cpp:80
#7 0x00000000005e513c in phxsql::PhxGLog::Log (level=1, format=0x7b3a23 "receive signal %d", args=0x7ffff8679e48) at phx_glog.cpp:66
#8 0x0000000000604367 in phxsql::LogError (format=0x7b3a23 "receive signal %d") at phx_log.cpp:160
#9 0x00000000005d2fb5 in SignalStop (signal_value=1) at phxsqlproxymain.cpp:55
#10 <signal handler called>
#11 0x00007fb6b5841afd in _int_malloc () from /lib64/libc.so.6
#12 0x00007fb6b58426b1 in malloc () from /lib64/libc.so.6
#13 0x0000000000753778 in operator new (sz=120) at ../../../../gcc-4.9.4/libstdc+-v3/libsupc+/new_op.cc:49
#14 0x00000000005d38e2 in phxsqlproxy::WorkerThread::InitRoutines<phxsqlproxy::MasterIORoutine> (this=0x27239a0, group_status_cache=0x26b29e0) at worker_thread.h:47
#15 0x00000000005d36b3 in StartWorker<phxsqlproxy::MasterIORoutine> (config=0x26b3090, worker_config=0x26b30f8) at phxsqlproxymain.cpp:135
#16 0x00000000005d3256 in phxsqlproxymain (argc=3, argv=0x7ffff867a818, config=0x26b3090) at phxsqlproxymain.cpp:175
#17 0x00000000005d2ed4 in main (argc=3, argv=0x7ffff867a818) at phxsqlproxymain_phxrpc.cpp:83

**Comment by wodesuck** [comment]
glog 里面调用了 malloc 导致。
fe46916 暂时删掉了这个 signal handler 里的内容。

**Comment by zqdai** [comment]
谢谢！
