### ISSUE TITLE
关于phxsync_phxrpc/init_with_phxbinlogsvr.cc:227行的一个小问题

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#96]
函数int BinlogGtidState::truncate_by_gtid中，227行似乎少了一个返回值的赋值操作？即：
truncate_one(new_binlog_filename_vector[i - 1].c_str(), sid_map, last_gtid);
似乎应为
truncate_one_ret = truncate_one(new_binlog_filename_vector[i - 1].c_str(), sid_map, last_gtid);

**Comment by wodesuck** [comment]
这地方调用 truncate_one 只是为了让它读 gtid，不会真正 truncate，跟上面的 truncate_one 用法不一样，可以忽略这个返回值。

**Comment by zqdai** [comment]
好的，谢谢！
