### ISSUE TITLE
请教关于binlog发送的问题

### ISSUE THREAD

**Issue by zqdai** [tencent-wechat/phxsql#97]
代码中目前binlog发送的逻辑似乎对于同一个事务是一次性发送的，然而paxos对于一次确定的值的大小有限制。所以想请教一下：
1、对于比较大的binlog，是否可以分多次发送？
2、paxos目前在large buffer模式下的限制约为50MB，是否可以提高到更大？

谢谢！

**Comment by wodesuck** [comment]
目前对于超过 50M 的 binlog 没有特殊处理，会发送失败，因为这样的需求在实际应用中也很少见。

可能以后会考虑搞一下。

**Comment by zqdai** [comment]
噢，好的。

再请教一下这行代码，文件phxbinlog_client.cpp，函数PhxBinlogClient::SendBinLog()中，
    stub_interface_->SetTimeOutMS(-1);
这行代码其实会导致以下错误，从而使得这个设置失去意义：
   setsockopt(60) errno 33, Numerical argument out of domain


    stub_interface_->SetTimeOutMS(-1);

**Comment by wodesuck** [comment]
是的，已改，多谢反馈。

**Comment by zqdai** [comment]
谢谢！

暂时先不close了，因为我这边还是能看到在binlog约15MB时会随机发生一些问题，我收集一些具体的东西稍后也发到这个楼里。

**Comment by zqdai** [comment]
根据我们目前的测试情况，当一个事务一次性插入数据约40MB时（使用tpcc-mysql load数据时），发现rpc性能严重下降：
1、rpc至少需要耗时2分钟。而paxos则只需要3秒钟左右就把数据同步到了其他2台机器。
2、在机器负载比较高时（同时运行各种其他的服务），phxsql 的 rpc性能下降更为明显，发送40MB数据约耗时13分钟，而且需要多次重试才能成功。

而且，在事务发送binlog期间，因为binlogsvr不断监控mysql的状态，从而产生大量的死亡线程等待被清理，尤其是show status like 'slave_running'; 这个语句在此期间实际上完全不能执行成功，在耗时很长时，mysql会崩溃。

不知你们是否遇到过类似的问题？谢谢！

**Comment by lynncui00** [comment]
您好，这个问题是我们很早发现的问题，跟PhxRPC框架有关，现在检查发现漏提交了代码。刚才我已经在PhxRPC的master版本修复了，你可以更新一下。或者直接修改本地代码先测试，只有一句代码改动。

phxrpc/http/http_msg.cpp  67行 content_.reserve(total); 注释掉这一行即可。

**Comment by zqdai** [comment]
谢谢！注释掉之后果然速度正常了！
